/**
 * SMIS2-CORE REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.Calendar;
import io.swagger.client.model.SComm;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class SOrg {
  
  @SerializedName("addition")
  private String addition = null;
  @SerializedName("comms")
  private List<SComm> comms = null;
  @SerializedName("country")
  private String country = null;
  @SerializedName("createDate")
  private Calendar createDate = null;
  @SerializedName("createUser")
  private Long createUser = null;
  @SerializedName("docboxTestEnv")
  private Boolean docboxTestEnv = null;
  @SerializedName("docboxUsername")
  private String docboxUsername = null;
  @SerializedName("ean")
  private String ean = null;
  @SerializedName("hpvKt1")
  private Integer hpvKt1 = null;
  @SerializedName("hpvKt2")
  private Integer hpvKt2 = null;
  @SerializedName("hpvKt3")
  private Integer hpvKt3 = null;
  @SerializedName("hpvOrdersAllowed")
  private Boolean hpvOrdersAllowed = null;
  @SerializedName("iban")
  private String iban = null;
  @SerializedName("locality")
  private String locality = null;
  @SerializedName("loginType")
  private Integer loginType = null;
  @SerializedName("meddocbox")
  private Boolean meddocbox = null;
  @SerializedName("medrx")
  private Boolean medrx = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("ndma")
  private Boolean ndma = null;
  @SerializedName("orgId")
  private Long orgId = null;
  @SerializedName("orgTypeId")
  private Integer orgTypeId = null;
  @SerializedName("poBox")
  private String poBox = null;
  @SerializedName("postAccount")
  private String postAccount = null;
  @SerializedName("prefersDoxboxReferrals")
  private Boolean prefersDoxboxReferrals = null;
  @SerializedName("prepandemiaCanton")
  private Integer prepandemiaCanton = null;
  @SerializedName("prepandemiaProvider")
  private Boolean prepandemiaProvider = null;
  @SerializedName("state")
  private String state = null;
  @SerializedName("status")
  private Integer status = null;
  @SerializedName("street")
  private String street = null;
  @SerializedName("tamifluProvider")
  private Boolean tamifluProvider = null;
  @SerializedName("title")
  private String title = null;
  @SerializedName("updateDate")
  private Calendar updateDate = null;
  @SerializedName("updateUser")
  private Long updateUser = null;
  @SerializedName("zip")
  private String zip = null;
  @SerializedName("zsrNumber")
  private String zsrNumber = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getAddition() {
    return addition;
  }
  public void setAddition(String addition) {
    this.addition = addition;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<SComm> getComms() {
    return comms;
  }
  public void setComms(List<SComm> comms) {
    this.comms = comms;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCountry() {
    return country;
  }
  public void setCountry(String country) {
    this.country = country;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Calendar getCreateDate() {
    return createDate;
  }
  public void setCreateDate(Calendar createDate) {
    this.createDate = createDate;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Long getCreateUser() {
    return createUser;
  }
  public void setCreateUser(Long createUser) {
    this.createUser = createUser;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getDocboxTestEnv() {
    return docboxTestEnv;
  }
  public void setDocboxTestEnv(Boolean docboxTestEnv) {
    this.docboxTestEnv = docboxTestEnv;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getDocboxUsername() {
    return docboxUsername;
  }
  public void setDocboxUsername(String docboxUsername) {
    this.docboxUsername = docboxUsername;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getEan() {
    return ean;
  }
  public void setEan(String ean) {
    this.ean = ean;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getHpvKt1() {
    return hpvKt1;
  }
  public void setHpvKt1(Integer hpvKt1) {
    this.hpvKt1 = hpvKt1;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getHpvKt2() {
    return hpvKt2;
  }
  public void setHpvKt2(Integer hpvKt2) {
    this.hpvKt2 = hpvKt2;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getHpvKt3() {
    return hpvKt3;
  }
  public void setHpvKt3(Integer hpvKt3) {
    this.hpvKt3 = hpvKt3;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getHpvOrdersAllowed() {
    return hpvOrdersAllowed;
  }
  public void setHpvOrdersAllowed(Boolean hpvOrdersAllowed) {
    this.hpvOrdersAllowed = hpvOrdersAllowed;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getIban() {
    return iban;
  }
  public void setIban(String iban) {
    this.iban = iban;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getLocality() {
    return locality;
  }
  public void setLocality(String locality) {
    this.locality = locality;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getLoginType() {
    return loginType;
  }
  public void setLoginType(Integer loginType) {
    this.loginType = loginType;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getMeddocbox() {
    return meddocbox;
  }
  public void setMeddocbox(Boolean meddocbox) {
    this.meddocbox = meddocbox;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getMedrx() {
    return medrx;
  }
  public void setMedrx(Boolean medrx) {
    this.medrx = medrx;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getNdma() {
    return ndma;
  }
  public void setNdma(Boolean ndma) {
    this.ndma = ndma;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Long getOrgId() {
    return orgId;
  }
  public void setOrgId(Long orgId) {
    this.orgId = orgId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getOrgTypeId() {
    return orgTypeId;
  }
  public void setOrgTypeId(Integer orgTypeId) {
    this.orgTypeId = orgTypeId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getPoBox() {
    return poBox;
  }
  public void setPoBox(String poBox) {
    this.poBox = poBox;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getPostAccount() {
    return postAccount;
  }
  public void setPostAccount(String postAccount) {
    this.postAccount = postAccount;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getPrefersDoxboxReferrals() {
    return prefersDoxboxReferrals;
  }
  public void setPrefersDoxboxReferrals(Boolean prefersDoxboxReferrals) {
    this.prefersDoxboxReferrals = prefersDoxboxReferrals;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getPrepandemiaCanton() {
    return prepandemiaCanton;
  }
  public void setPrepandemiaCanton(Integer prepandemiaCanton) {
    this.prepandemiaCanton = prepandemiaCanton;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getPrepandemiaProvider() {
    return prepandemiaProvider;
  }
  public void setPrepandemiaProvider(Boolean prepandemiaProvider) {
    this.prepandemiaProvider = prepandemiaProvider;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getState() {
    return state;
  }
  public void setState(String state) {
    this.state = state;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getStatus() {
    return status;
  }
  public void setStatus(Integer status) {
    this.status = status;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getStreet() {
    return street;
  }
  public void setStreet(String street) {
    this.street = street;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getTamifluProvider() {
    return tamifluProvider;
  }
  public void setTamifluProvider(Boolean tamifluProvider) {
    this.tamifluProvider = tamifluProvider;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getTitle() {
    return title;
  }
  public void setTitle(String title) {
    this.title = title;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Calendar getUpdateDate() {
    return updateDate;
  }
  public void setUpdateDate(Calendar updateDate) {
    this.updateDate = updateDate;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Long getUpdateUser() {
    return updateUser;
  }
  public void setUpdateUser(Long updateUser) {
    this.updateUser = updateUser;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getZip() {
    return zip;
  }
  public void setZip(String zip) {
    this.zip = zip;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getZsrNumber() {
    return zsrNumber;
  }
  public void setZsrNumber(String zsrNumber) {
    this.zsrNumber = zsrNumber;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SOrg sOrg = (SOrg) o;
    return (this.addition == null ? sOrg.addition == null : this.addition.equals(sOrg.addition)) &&
        (this.comms == null ? sOrg.comms == null : this.comms.equals(sOrg.comms)) &&
        (this.country == null ? sOrg.country == null : this.country.equals(sOrg.country)) &&
        (this.createDate == null ? sOrg.createDate == null : this.createDate.equals(sOrg.createDate)) &&
        (this.createUser == null ? sOrg.createUser == null : this.createUser.equals(sOrg.createUser)) &&
        (this.docboxTestEnv == null ? sOrg.docboxTestEnv == null : this.docboxTestEnv.equals(sOrg.docboxTestEnv)) &&
        (this.docboxUsername == null ? sOrg.docboxUsername == null : this.docboxUsername.equals(sOrg.docboxUsername)) &&
        (this.ean == null ? sOrg.ean == null : this.ean.equals(sOrg.ean)) &&
        (this.hpvKt1 == null ? sOrg.hpvKt1 == null : this.hpvKt1.equals(sOrg.hpvKt1)) &&
        (this.hpvKt2 == null ? sOrg.hpvKt2 == null : this.hpvKt2.equals(sOrg.hpvKt2)) &&
        (this.hpvKt3 == null ? sOrg.hpvKt3 == null : this.hpvKt3.equals(sOrg.hpvKt3)) &&
        (this.hpvOrdersAllowed == null ? sOrg.hpvOrdersAllowed == null : this.hpvOrdersAllowed.equals(sOrg.hpvOrdersAllowed)) &&
        (this.iban == null ? sOrg.iban == null : this.iban.equals(sOrg.iban)) &&
        (this.locality == null ? sOrg.locality == null : this.locality.equals(sOrg.locality)) &&
        (this.loginType == null ? sOrg.loginType == null : this.loginType.equals(sOrg.loginType)) &&
        (this.meddocbox == null ? sOrg.meddocbox == null : this.meddocbox.equals(sOrg.meddocbox)) &&
        (this.medrx == null ? sOrg.medrx == null : this.medrx.equals(sOrg.medrx)) &&
        (this.name == null ? sOrg.name == null : this.name.equals(sOrg.name)) &&
        (this.ndma == null ? sOrg.ndma == null : this.ndma.equals(sOrg.ndma)) &&
        (this.orgId == null ? sOrg.orgId == null : this.orgId.equals(sOrg.orgId)) &&
        (this.orgTypeId == null ? sOrg.orgTypeId == null : this.orgTypeId.equals(sOrg.orgTypeId)) &&
        (this.poBox == null ? sOrg.poBox == null : this.poBox.equals(sOrg.poBox)) &&
        (this.postAccount == null ? sOrg.postAccount == null : this.postAccount.equals(sOrg.postAccount)) &&
        (this.prefersDoxboxReferrals == null ? sOrg.prefersDoxboxReferrals == null : this.prefersDoxboxReferrals.equals(sOrg.prefersDoxboxReferrals)) &&
        (this.prepandemiaCanton == null ? sOrg.prepandemiaCanton == null : this.prepandemiaCanton.equals(sOrg.prepandemiaCanton)) &&
        (this.prepandemiaProvider == null ? sOrg.prepandemiaProvider == null : this.prepandemiaProvider.equals(sOrg.prepandemiaProvider)) &&
        (this.state == null ? sOrg.state == null : this.state.equals(sOrg.state)) &&
        (this.status == null ? sOrg.status == null : this.status.equals(sOrg.status)) &&
        (this.street == null ? sOrg.street == null : this.street.equals(sOrg.street)) &&
        (this.tamifluProvider == null ? sOrg.tamifluProvider == null : this.tamifluProvider.equals(sOrg.tamifluProvider)) &&
        (this.title == null ? sOrg.title == null : this.title.equals(sOrg.title)) &&
        (this.updateDate == null ? sOrg.updateDate == null : this.updateDate.equals(sOrg.updateDate)) &&
        (this.updateUser == null ? sOrg.updateUser == null : this.updateUser.equals(sOrg.updateUser)) &&
        (this.zip == null ? sOrg.zip == null : this.zip.equals(sOrg.zip)) &&
        (this.zsrNumber == null ? sOrg.zsrNumber == null : this.zsrNumber.equals(sOrg.zsrNumber));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.addition == null ? 0: this.addition.hashCode());
    result = 31 * result + (this.comms == null ? 0: this.comms.hashCode());
    result = 31 * result + (this.country == null ? 0: this.country.hashCode());
    result = 31 * result + (this.createDate == null ? 0: this.createDate.hashCode());
    result = 31 * result + (this.createUser == null ? 0: this.createUser.hashCode());
    result = 31 * result + (this.docboxTestEnv == null ? 0: this.docboxTestEnv.hashCode());
    result = 31 * result + (this.docboxUsername == null ? 0: this.docboxUsername.hashCode());
    result = 31 * result + (this.ean == null ? 0: this.ean.hashCode());
    result = 31 * result + (this.hpvKt1 == null ? 0: this.hpvKt1.hashCode());
    result = 31 * result + (this.hpvKt2 == null ? 0: this.hpvKt2.hashCode());
    result = 31 * result + (this.hpvKt3 == null ? 0: this.hpvKt3.hashCode());
    result = 31 * result + (this.hpvOrdersAllowed == null ? 0: this.hpvOrdersAllowed.hashCode());
    result = 31 * result + (this.iban == null ? 0: this.iban.hashCode());
    result = 31 * result + (this.locality == null ? 0: this.locality.hashCode());
    result = 31 * result + (this.loginType == null ? 0: this.loginType.hashCode());
    result = 31 * result + (this.meddocbox == null ? 0: this.meddocbox.hashCode());
    result = 31 * result + (this.medrx == null ? 0: this.medrx.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.ndma == null ? 0: this.ndma.hashCode());
    result = 31 * result + (this.orgId == null ? 0: this.orgId.hashCode());
    result = 31 * result + (this.orgTypeId == null ? 0: this.orgTypeId.hashCode());
    result = 31 * result + (this.poBox == null ? 0: this.poBox.hashCode());
    result = 31 * result + (this.postAccount == null ? 0: this.postAccount.hashCode());
    result = 31 * result + (this.prefersDoxboxReferrals == null ? 0: this.prefersDoxboxReferrals.hashCode());
    result = 31 * result + (this.prepandemiaCanton == null ? 0: this.prepandemiaCanton.hashCode());
    result = 31 * result + (this.prepandemiaProvider == null ? 0: this.prepandemiaProvider.hashCode());
    result = 31 * result + (this.state == null ? 0: this.state.hashCode());
    result = 31 * result + (this.status == null ? 0: this.status.hashCode());
    result = 31 * result + (this.street == null ? 0: this.street.hashCode());
    result = 31 * result + (this.tamifluProvider == null ? 0: this.tamifluProvider.hashCode());
    result = 31 * result + (this.title == null ? 0: this.title.hashCode());
    result = 31 * result + (this.updateDate == null ? 0: this.updateDate.hashCode());
    result = 31 * result + (this.updateUser == null ? 0: this.updateUser.hashCode());
    result = 31 * result + (this.zip == null ? 0: this.zip.hashCode());
    result = 31 * result + (this.zsrNumber == null ? 0: this.zsrNumber.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SOrg {\n");
    
    sb.append("  addition: ").append(addition).append("\n");
    sb.append("  comms: ").append(comms).append("\n");
    sb.append("  country: ").append(country).append("\n");
    sb.append("  createDate: ").append(createDate).append("\n");
    sb.append("  createUser: ").append(createUser).append("\n");
    sb.append("  docboxTestEnv: ").append(docboxTestEnv).append("\n");
    sb.append("  docboxUsername: ").append(docboxUsername).append("\n");
    sb.append("  ean: ").append(ean).append("\n");
    sb.append("  hpvKt1: ").append(hpvKt1).append("\n");
    sb.append("  hpvKt2: ").append(hpvKt2).append("\n");
    sb.append("  hpvKt3: ").append(hpvKt3).append("\n");
    sb.append("  hpvOrdersAllowed: ").append(hpvOrdersAllowed).append("\n");
    sb.append("  iban: ").append(iban).append("\n");
    sb.append("  locality: ").append(locality).append("\n");
    sb.append("  loginType: ").append(loginType).append("\n");
    sb.append("  meddocbox: ").append(meddocbox).append("\n");
    sb.append("  medrx: ").append(medrx).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  ndma: ").append(ndma).append("\n");
    sb.append("  orgId: ").append(orgId).append("\n");
    sb.append("  orgTypeId: ").append(orgTypeId).append("\n");
    sb.append("  poBox: ").append(poBox).append("\n");
    sb.append("  postAccount: ").append(postAccount).append("\n");
    sb.append("  prefersDoxboxReferrals: ").append(prefersDoxboxReferrals).append("\n");
    sb.append("  prepandemiaCanton: ").append(prepandemiaCanton).append("\n");
    sb.append("  prepandemiaProvider: ").append(prepandemiaProvider).append("\n");
    sb.append("  state: ").append(state).append("\n");
    sb.append("  status: ").append(status).append("\n");
    sb.append("  street: ").append(street).append("\n");
    sb.append("  tamifluProvider: ").append(tamifluProvider).append("\n");
    sb.append("  title: ").append(title).append("\n");
    sb.append("  updateDate: ").append(updateDate).append("\n");
    sb.append("  updateUser: ").append(updateUser).append("\n");
    sb.append("  zip: ").append(zip).append("\n");
    sb.append("  zsrNumber: ").append(zsrNumber).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
