/**
 * SMIS2-CORE REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class SOrgPatientPK {
  
  @SerializedName("orgId")
  private Long orgId = null;
  @SerializedName("patientId")
  private Long patientId = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Long getOrgId() {
    return orgId;
  }
  public void setOrgId(Long orgId) {
    this.orgId = orgId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Long getPatientId() {
    return patientId;
  }
  public void setPatientId(Long patientId) {
    this.patientId = patientId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SOrgPatientPK sOrgPatientPK = (SOrgPatientPK) o;
    return (this.orgId == null ? sOrgPatientPK.orgId == null : this.orgId.equals(sOrgPatientPK.orgId)) &&
        (this.patientId == null ? sOrgPatientPK.patientId == null : this.patientId.equals(sOrgPatientPK.patientId));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.orgId == null ? 0: this.orgId.hashCode());
    result = 31 * result + (this.patientId == null ? 0: this.patientId.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SOrgPatientPK {\n");
    
    sb.append("  orgId: ").append(orgId).append("\n");
    sb.append("  patientId: ").append(patientId).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
