/**
 * SMIS2-CORE REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class SOrgGroup {
  
  @SerializedName("groupId")
  private Integer groupId = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("orgId")
  private Long orgId = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getGroupId() {
    return groupId;
  }
  public void setGroupId(Integer groupId) {
    this.groupId = groupId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Long getOrgId() {
    return orgId;
  }
  public void setOrgId(Long orgId) {
    this.orgId = orgId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SOrgGroup sOrgGroup = (SOrgGroup) o;
    return (this.groupId == null ? sOrgGroup.groupId == null : this.groupId.equals(sOrgGroup.groupId)) &&
        (this.name == null ? sOrgGroup.name == null : this.name.equals(sOrgGroup.name)) &&
        (this.orgId == null ? sOrgGroup.orgId == null : this.orgId.equals(sOrgGroup.orgId));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.groupId == null ? 0: this.groupId.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.orgId == null ? 0: this.orgId.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SOrgGroup {\n");
    
    sb.append("  groupId: ").append(groupId).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  orgId: ").append(orgId).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
