/**
 * SMIS2-CORE REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.Calendar;
import io.swagger.client.model.SComm;
import io.swagger.client.model.SOrgPatientPK;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class SOrgPatient {
  
  @SerializedName("ahvNumber")
  private String ahvNumber = null;
  @SerializedName("birthdate")
  private Calendar birthdate = null;
  @SerializedName("comms")
  private List<SComm> comms = null;
  @SerializedName("country")
  private String country = null;
  @SerializedName("createDate")
  private Calendar createDate = null;
  @SerializedName("createUser")
  private Long createUser = null;
  @SerializedName("deleted")
  private Boolean deleted = null;
  @SerializedName("employerAddress")
  private String employerAddress = null;
  @SerializedName("employerLocality")
  private String employerLocality = null;
  @SerializedName("employerName")
  private String employerName = null;
  @SerializedName("employerZip")
  private String employerZip = null;
  @SerializedName("evitaCustomerNo")
  private String evitaCustomerNo = null;
  @SerializedName("firstName")
  private String firstName = null;
  @SerializedName("flags")
  private String flags = null;
  @SerializedName("gender")
  private Integer gender = null;
  @SerializedName("groupIds")
  private List<Integer> groupIds = null;
  @SerializedName("guardianAddrress")
  private String guardianAddrress = null;
  @SerializedName("guardianLocality")
  private String guardianLocality = null;
  @SerializedName("guardianName")
  private String guardianName = null;
  @SerializedName("guardianPhone")
  private String guardianPhone = null;
  @SerializedName("guardianZip")
  private String guardianZip = null;
  @SerializedName("hpv")
  private Integer hpv = null;
  @SerializedName("id")
  private SOrgPatientPK id = null;
  @SerializedName("inactive")
  private Boolean inactive = null;
  @SerializedName("lastName")
  private String lastName = null;
  @SerializedName("lastSeen")
  private Calendar lastSeen = null;
  @SerializedName("locality")
  private String locality = null;
  @SerializedName("medicId")
  private String medicId = null;
  @SerializedName("orgMedicId")
  private Long orgMedicId = null;
  @SerializedName("orgName")
  private String orgName = null;
  @SerializedName("orgPatientId")
  private String orgPatientId = null;
  @SerializedName("poBox")
  private String poBox = null;
  @SerializedName("profession")
  private String profession = null;
  @SerializedName("socialInsuranceNumber")
  private String socialInsuranceNumber = null;
  @SerializedName("state")
  private String state = null;
  @SerializedName("street")
  private String street = null;
  @SerializedName("title")
  private String title = null;
  @SerializedName("updateDate")
  private Calendar updateDate = null;
  @SerializedName("updateUser")
  private Long updateUser = null;
  @SerializedName("valid")
  private Boolean valid = null;
  @SerializedName("zip")
  private String zip = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getAhvNumber() {
    return ahvNumber;
  }
  public void setAhvNumber(String ahvNumber) {
    this.ahvNumber = ahvNumber;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Calendar getBirthdate() {
    return birthdate;
  }
  public void setBirthdate(Calendar birthdate) {
    this.birthdate = birthdate;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<SComm> getComms() {
    return comms;
  }
  public void setComms(List<SComm> comms) {
    this.comms = comms;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCountry() {
    return country;
  }
  public void setCountry(String country) {
    this.country = country;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Calendar getCreateDate() {
    return createDate;
  }
  public void setCreateDate(Calendar createDate) {
    this.createDate = createDate;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Long getCreateUser() {
    return createUser;
  }
  public void setCreateUser(Long createUser) {
    this.createUser = createUser;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getDeleted() {
    return deleted;
  }
  public void setDeleted(Boolean deleted) {
    this.deleted = deleted;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getEmployerAddress() {
    return employerAddress;
  }
  public void setEmployerAddress(String employerAddress) {
    this.employerAddress = employerAddress;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getEmployerLocality() {
    return employerLocality;
  }
  public void setEmployerLocality(String employerLocality) {
    this.employerLocality = employerLocality;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getEmployerName() {
    return employerName;
  }
  public void setEmployerName(String employerName) {
    this.employerName = employerName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getEmployerZip() {
    return employerZip;
  }
  public void setEmployerZip(String employerZip) {
    this.employerZip = employerZip;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getEvitaCustomerNo() {
    return evitaCustomerNo;
  }
  public void setEvitaCustomerNo(String evitaCustomerNo) {
    this.evitaCustomerNo = evitaCustomerNo;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getFirstName() {
    return firstName;
  }
  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getFlags() {
    return flags;
  }
  public void setFlags(String flags) {
    this.flags = flags;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getGender() {
    return gender;
  }
  public void setGender(Integer gender) {
    this.gender = gender;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<Integer> getGroupIds() {
    return groupIds;
  }
  public void setGroupIds(List<Integer> groupIds) {
    this.groupIds = groupIds;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getGuardianAddrress() {
    return guardianAddrress;
  }
  public void setGuardianAddrress(String guardianAddrress) {
    this.guardianAddrress = guardianAddrress;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getGuardianLocality() {
    return guardianLocality;
  }
  public void setGuardianLocality(String guardianLocality) {
    this.guardianLocality = guardianLocality;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getGuardianName() {
    return guardianName;
  }
  public void setGuardianName(String guardianName) {
    this.guardianName = guardianName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getGuardianPhone() {
    return guardianPhone;
  }
  public void setGuardianPhone(String guardianPhone) {
    this.guardianPhone = guardianPhone;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getGuardianZip() {
    return guardianZip;
  }
  public void setGuardianZip(String guardianZip) {
    this.guardianZip = guardianZip;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getHpv() {
    return hpv;
  }
  public void setHpv(Integer hpv) {
    this.hpv = hpv;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public SOrgPatientPK getId() {
    return id;
  }
  public void setId(SOrgPatientPK id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getInactive() {
    return inactive;
  }
  public void setInactive(Boolean inactive) {
    this.inactive = inactive;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getLastName() {
    return lastName;
  }
  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Calendar getLastSeen() {
    return lastSeen;
  }
  public void setLastSeen(Calendar lastSeen) {
    this.lastSeen = lastSeen;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getLocality() {
    return locality;
  }
  public void setLocality(String locality) {
    this.locality = locality;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getMedicId() {
    return medicId;
  }
  public void setMedicId(String medicId) {
    this.medicId = medicId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Long getOrgMedicId() {
    return orgMedicId;
  }
  public void setOrgMedicId(Long orgMedicId) {
    this.orgMedicId = orgMedicId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getOrgName() {
    return orgName;
  }
  public void setOrgName(String orgName) {
    this.orgName = orgName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getOrgPatientId() {
    return orgPatientId;
  }
  public void setOrgPatientId(String orgPatientId) {
    this.orgPatientId = orgPatientId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getPoBox() {
    return poBox;
  }
  public void setPoBox(String poBox) {
    this.poBox = poBox;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getProfession() {
    return profession;
  }
  public void setProfession(String profession) {
    this.profession = profession;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getSocialInsuranceNumber() {
    return socialInsuranceNumber;
  }
  public void setSocialInsuranceNumber(String socialInsuranceNumber) {
    this.socialInsuranceNumber = socialInsuranceNumber;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getState() {
    return state;
  }
  public void setState(String state) {
    this.state = state;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getStreet() {
    return street;
  }
  public void setStreet(String street) {
    this.street = street;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getTitle() {
    return title;
  }
  public void setTitle(String title) {
    this.title = title;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Calendar getUpdateDate() {
    return updateDate;
  }
  public void setUpdateDate(Calendar updateDate) {
    this.updateDate = updateDate;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Long getUpdateUser() {
    return updateUser;
  }
  public void setUpdateUser(Long updateUser) {
    this.updateUser = updateUser;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getValid() {
    return valid;
  }
  public void setValid(Boolean valid) {
    this.valid = valid;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getZip() {
    return zip;
  }
  public void setZip(String zip) {
    this.zip = zip;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SOrgPatient sOrgPatient = (SOrgPatient) o;
    return (this.ahvNumber == null ? sOrgPatient.ahvNumber == null : this.ahvNumber.equals(sOrgPatient.ahvNumber)) &&
        (this.birthdate == null ? sOrgPatient.birthdate == null : this.birthdate.equals(sOrgPatient.birthdate)) &&
        (this.comms == null ? sOrgPatient.comms == null : this.comms.equals(sOrgPatient.comms)) &&
        (this.country == null ? sOrgPatient.country == null : this.country.equals(sOrgPatient.country)) &&
        (this.createDate == null ? sOrgPatient.createDate == null : this.createDate.equals(sOrgPatient.createDate)) &&
        (this.createUser == null ? sOrgPatient.createUser == null : this.createUser.equals(sOrgPatient.createUser)) &&
        (this.deleted == null ? sOrgPatient.deleted == null : this.deleted.equals(sOrgPatient.deleted)) &&
        (this.employerAddress == null ? sOrgPatient.employerAddress == null : this.employerAddress.equals(sOrgPatient.employerAddress)) &&
        (this.employerLocality == null ? sOrgPatient.employerLocality == null : this.employerLocality.equals(sOrgPatient.employerLocality)) &&
        (this.employerName == null ? sOrgPatient.employerName == null : this.employerName.equals(sOrgPatient.employerName)) &&
        (this.employerZip == null ? sOrgPatient.employerZip == null : this.employerZip.equals(sOrgPatient.employerZip)) &&
        (this.evitaCustomerNo == null ? sOrgPatient.evitaCustomerNo == null : this.evitaCustomerNo.equals(sOrgPatient.evitaCustomerNo)) &&
        (this.firstName == null ? sOrgPatient.firstName == null : this.firstName.equals(sOrgPatient.firstName)) &&
        (this.flags == null ? sOrgPatient.flags == null : this.flags.equals(sOrgPatient.flags)) &&
        (this.gender == null ? sOrgPatient.gender == null : this.gender.equals(sOrgPatient.gender)) &&
        (this.groupIds == null ? sOrgPatient.groupIds == null : this.groupIds.equals(sOrgPatient.groupIds)) &&
        (this.guardianAddrress == null ? sOrgPatient.guardianAddrress == null : this.guardianAddrress.equals(sOrgPatient.guardianAddrress)) &&
        (this.guardianLocality == null ? sOrgPatient.guardianLocality == null : this.guardianLocality.equals(sOrgPatient.guardianLocality)) &&
        (this.guardianName == null ? sOrgPatient.guardianName == null : this.guardianName.equals(sOrgPatient.guardianName)) &&
        (this.guardianPhone == null ? sOrgPatient.guardianPhone == null : this.guardianPhone.equals(sOrgPatient.guardianPhone)) &&
        (this.guardianZip == null ? sOrgPatient.guardianZip == null : this.guardianZip.equals(sOrgPatient.guardianZip)) &&
        (this.hpv == null ? sOrgPatient.hpv == null : this.hpv.equals(sOrgPatient.hpv)) &&
        (this.id == null ? sOrgPatient.id == null : this.id.equals(sOrgPatient.id)) &&
        (this.inactive == null ? sOrgPatient.inactive == null : this.inactive.equals(sOrgPatient.inactive)) &&
        (this.lastName == null ? sOrgPatient.lastName == null : this.lastName.equals(sOrgPatient.lastName)) &&
        (this.lastSeen == null ? sOrgPatient.lastSeen == null : this.lastSeen.equals(sOrgPatient.lastSeen)) &&
        (this.locality == null ? sOrgPatient.locality == null : this.locality.equals(sOrgPatient.locality)) &&
        (this.medicId == null ? sOrgPatient.medicId == null : this.medicId.equals(sOrgPatient.medicId)) &&
        (this.orgMedicId == null ? sOrgPatient.orgMedicId == null : this.orgMedicId.equals(sOrgPatient.orgMedicId)) &&
        (this.orgName == null ? sOrgPatient.orgName == null : this.orgName.equals(sOrgPatient.orgName)) &&
        (this.orgPatientId == null ? sOrgPatient.orgPatientId == null : this.orgPatientId.equals(sOrgPatient.orgPatientId)) &&
        (this.poBox == null ? sOrgPatient.poBox == null : this.poBox.equals(sOrgPatient.poBox)) &&
        (this.profession == null ? sOrgPatient.profession == null : this.profession.equals(sOrgPatient.profession)) &&
        (this.socialInsuranceNumber == null ? sOrgPatient.socialInsuranceNumber == null : this.socialInsuranceNumber.equals(sOrgPatient.socialInsuranceNumber)) &&
        (this.state == null ? sOrgPatient.state == null : this.state.equals(sOrgPatient.state)) &&
        (this.street == null ? sOrgPatient.street == null : this.street.equals(sOrgPatient.street)) &&
        (this.title == null ? sOrgPatient.title == null : this.title.equals(sOrgPatient.title)) &&
        (this.updateDate == null ? sOrgPatient.updateDate == null : this.updateDate.equals(sOrgPatient.updateDate)) &&
        (this.updateUser == null ? sOrgPatient.updateUser == null : this.updateUser.equals(sOrgPatient.updateUser)) &&
        (this.valid == null ? sOrgPatient.valid == null : this.valid.equals(sOrgPatient.valid)) &&
        (this.zip == null ? sOrgPatient.zip == null : this.zip.equals(sOrgPatient.zip));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.ahvNumber == null ? 0: this.ahvNumber.hashCode());
    result = 31 * result + (this.birthdate == null ? 0: this.birthdate.hashCode());
    result = 31 * result + (this.comms == null ? 0: this.comms.hashCode());
    result = 31 * result + (this.country == null ? 0: this.country.hashCode());
    result = 31 * result + (this.createDate == null ? 0: this.createDate.hashCode());
    result = 31 * result + (this.createUser == null ? 0: this.createUser.hashCode());
    result = 31 * result + (this.deleted == null ? 0: this.deleted.hashCode());
    result = 31 * result + (this.employerAddress == null ? 0: this.employerAddress.hashCode());
    result = 31 * result + (this.employerLocality == null ? 0: this.employerLocality.hashCode());
    result = 31 * result + (this.employerName == null ? 0: this.employerName.hashCode());
    result = 31 * result + (this.employerZip == null ? 0: this.employerZip.hashCode());
    result = 31 * result + (this.evitaCustomerNo == null ? 0: this.evitaCustomerNo.hashCode());
    result = 31 * result + (this.firstName == null ? 0: this.firstName.hashCode());
    result = 31 * result + (this.flags == null ? 0: this.flags.hashCode());
    result = 31 * result + (this.gender == null ? 0: this.gender.hashCode());
    result = 31 * result + (this.groupIds == null ? 0: this.groupIds.hashCode());
    result = 31 * result + (this.guardianAddrress == null ? 0: this.guardianAddrress.hashCode());
    result = 31 * result + (this.guardianLocality == null ? 0: this.guardianLocality.hashCode());
    result = 31 * result + (this.guardianName == null ? 0: this.guardianName.hashCode());
    result = 31 * result + (this.guardianPhone == null ? 0: this.guardianPhone.hashCode());
    result = 31 * result + (this.guardianZip == null ? 0: this.guardianZip.hashCode());
    result = 31 * result + (this.hpv == null ? 0: this.hpv.hashCode());
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.inactive == null ? 0: this.inactive.hashCode());
    result = 31 * result + (this.lastName == null ? 0: this.lastName.hashCode());
    result = 31 * result + (this.lastSeen == null ? 0: this.lastSeen.hashCode());
    result = 31 * result + (this.locality == null ? 0: this.locality.hashCode());
    result = 31 * result + (this.medicId == null ? 0: this.medicId.hashCode());
    result = 31 * result + (this.orgMedicId == null ? 0: this.orgMedicId.hashCode());
    result = 31 * result + (this.orgName == null ? 0: this.orgName.hashCode());
    result = 31 * result + (this.orgPatientId == null ? 0: this.orgPatientId.hashCode());
    result = 31 * result + (this.poBox == null ? 0: this.poBox.hashCode());
    result = 31 * result + (this.profession == null ? 0: this.profession.hashCode());
    result = 31 * result + (this.socialInsuranceNumber == null ? 0: this.socialInsuranceNumber.hashCode());
    result = 31 * result + (this.state == null ? 0: this.state.hashCode());
    result = 31 * result + (this.street == null ? 0: this.street.hashCode());
    result = 31 * result + (this.title == null ? 0: this.title.hashCode());
    result = 31 * result + (this.updateDate == null ? 0: this.updateDate.hashCode());
    result = 31 * result + (this.updateUser == null ? 0: this.updateUser.hashCode());
    result = 31 * result + (this.valid == null ? 0: this.valid.hashCode());
    result = 31 * result + (this.zip == null ? 0: this.zip.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SOrgPatient {\n");
    
    sb.append("  ahvNumber: ").append(ahvNumber).append("\n");
    sb.append("  birthdate: ").append(birthdate).append("\n");
    sb.append("  comms: ").append(comms).append("\n");
    sb.append("  country: ").append(country).append("\n");
    sb.append("  createDate: ").append(createDate).append("\n");
    sb.append("  createUser: ").append(createUser).append("\n");
    sb.append("  deleted: ").append(deleted).append("\n");
    sb.append("  employerAddress: ").append(employerAddress).append("\n");
    sb.append("  employerLocality: ").append(employerLocality).append("\n");
    sb.append("  employerName: ").append(employerName).append("\n");
    sb.append("  employerZip: ").append(employerZip).append("\n");
    sb.append("  evitaCustomerNo: ").append(evitaCustomerNo).append("\n");
    sb.append("  firstName: ").append(firstName).append("\n");
    sb.append("  flags: ").append(flags).append("\n");
    sb.append("  gender: ").append(gender).append("\n");
    sb.append("  groupIds: ").append(groupIds).append("\n");
    sb.append("  guardianAddrress: ").append(guardianAddrress).append("\n");
    sb.append("  guardianLocality: ").append(guardianLocality).append("\n");
    sb.append("  guardianName: ").append(guardianName).append("\n");
    sb.append("  guardianPhone: ").append(guardianPhone).append("\n");
    sb.append("  guardianZip: ").append(guardianZip).append("\n");
    sb.append("  hpv: ").append(hpv).append("\n");
    sb.append("  id: ").append(id).append("\n");
    sb.append("  inactive: ").append(inactive).append("\n");
    sb.append("  lastName: ").append(lastName).append("\n");
    sb.append("  lastSeen: ").append(lastSeen).append("\n");
    sb.append("  locality: ").append(locality).append("\n");
    sb.append("  medicId: ").append(medicId).append("\n");
    sb.append("  orgMedicId: ").append(orgMedicId).append("\n");
    sb.append("  orgName: ").append(orgName).append("\n");
    sb.append("  orgPatientId: ").append(orgPatientId).append("\n");
    sb.append("  poBox: ").append(poBox).append("\n");
    sb.append("  profession: ").append(profession).append("\n");
    sb.append("  socialInsuranceNumber: ").append(socialInsuranceNumber).append("\n");
    sb.append("  state: ").append(state).append("\n");
    sb.append("  street: ").append(street).append("\n");
    sb.append("  title: ").append(title).append("\n");
    sb.append("  updateDate: ").append(updateDate).append("\n");
    sb.append("  updateUser: ").append(updateUser).append("\n");
    sb.append("  valid: ").append(valid).append("\n");
    sb.append("  zip: ").append(zip).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
