/**
 * SMIS2-CORE REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonParseException;
import com.google.gson.reflect.TypeToken;
import java.lang.reflect.Type;
import java.util.List;
import java.util.Date;
import io.swagger.client.model.*;

public class JsonUtil {
  public static GsonBuilder gsonBuilder;

  static {
    gsonBuilder = new GsonBuilder();
    gsonBuilder.serializeNulls();
    gsonBuilder.setDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ");
    gsonBuilder.registerTypeAdapter(Date.class, new JsonDeserializer<Date>() {
      public Date deserialize(JsonElement json, Type typeOfT, JsonDeserializationContext context) throws JsonParseException {
        return new Date(json.getAsJsonPrimitive().getAsLong());
      }
    });
  }

  public static Gson getGson() {
    return gsonBuilder.create();
  }

  public static String serialize(Object obj){
    return getGson().toJson(obj);
  }

  public static <T> T deserializeToList(String jsonString, Class cls){
    return getGson().fromJson(jsonString, getListTypeForDeserialization(cls));
  }

  public static <T> T deserializeToObject(String jsonString, Class cls){
    return getGson().fromJson(jsonString, getTypeForDeserialization(cls));
  }

  public static Type getListTypeForDeserialization(Class cls) {
    String className = cls.getSimpleName();
    
    if ("Calendar".equalsIgnoreCase(className)) {
      return new TypeToken<List<Calendar>>(){}.getType();
    }
    
    if ("SComm".equalsIgnoreCase(className)) {
      return new TypeToken<List<SComm>>(){}.getType();
    }
    
    if ("SOrg".equalsIgnoreCase(className)) {
      return new TypeToken<List<SOrg>>(){}.getType();
    }
    
    if ("SOrgGroup".equalsIgnoreCase(className)) {
      return new TypeToken<List<SOrgGroup>>(){}.getType();
    }
    
    if ("SOrgPatient".equalsIgnoreCase(className)) {
      return new TypeToken<List<SOrgPatient>>(){}.getType();
    }
    
    if ("SOrgPatientPK".equalsIgnoreCase(className)) {
      return new TypeToken<List<SOrgPatientPK>>(){}.getType();
    }
    
    if ("SOrgRole".equalsIgnoreCase(className)) {
      return new TypeToken<List<SOrgRole>>(){}.getType();
    }
    
    if ("TimeZone".equalsIgnoreCase(className)) {
      return new TypeToken<List<TimeZone>>(){}.getType();
    }
    
    return new TypeToken<List<Object>>(){}.getType();
  }

  public static Type getTypeForDeserialization(Class cls) {
    String className = cls.getSimpleName();
    
    if ("Calendar".equalsIgnoreCase(className)) {
      return new TypeToken<Calendar>(){}.getType();
    }
    
    if ("SComm".equalsIgnoreCase(className)) {
      return new TypeToken<SComm>(){}.getType();
    }
    
    if ("SOrg".equalsIgnoreCase(className)) {
      return new TypeToken<SOrg>(){}.getType();
    }
    
    if ("SOrgGroup".equalsIgnoreCase(className)) {
      return new TypeToken<SOrgGroup>(){}.getType();
    }
    
    if ("SOrgPatient".equalsIgnoreCase(className)) {
      return new TypeToken<SOrgPatient>(){}.getType();
    }
    
    if ("SOrgPatientPK".equalsIgnoreCase(className)) {
      return new TypeToken<SOrgPatientPK>(){}.getType();
    }
    
    if ("SOrgRole".equalsIgnoreCase(className)) {
      return new TypeToken<SOrgRole>(){}.getType();
    }
    
    if ("TimeZone".equalsIgnoreCase(className)) {
      return new TypeToken<TimeZone>(){}.getType();
    }
    
    return new TypeToken<Object>(){}.getType();
  }

};
