/**
 * SMIS2-CORE REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiInvoker;
import io.swagger.client.ApiException;
import io.swagger.client.Pair;

import io.swagger.client.model.*;

import java.util.*;

import com.android.volley.Response;
import com.android.volley.VolleyError;

import org.apache.http.HttpEntity;
import org.apache.http.entity.mime.MultipartEntityBuilder;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.TimeoutException;

public class SattachmentcontrollerApi {
  String basePath = "https://localhost:8080/smis2-core";
  ApiInvoker apiInvoker = ApiInvoker.getInstance();

  public void addHeader(String key, String value) {
    getInvoker().addDefaultHeader(key, value);
  }

  public ApiInvoker getInvoker() {
    return apiInvoker;
  }

  public void setBasePath(String basePath) {
    this.basePath = basePath;
  }

  public String getBasePath() {
    return basePath;
  }


  /**
  * deleteAttachment
  * deleteAttachment
   * @param orgId orgId
   * @param patientId patientId
   * @param elementId elementId
   * @param attachmentId attachmentId
   * @return String
  */
  public String deleteAttachmentUsingDELETE (Long orgId, Long patientId, Long elementId, Integer attachmentId) throws TimeoutException, ExecutionException, InterruptedException, ApiException {
    Object postBody = null;
    // verify the required parameter 'orgId' is set
    if (orgId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'orgId' when calling deleteAttachmentUsingDELETE",
        new ApiException(400, "Missing the required parameter 'orgId' when calling deleteAttachmentUsingDELETE"));
    }
    // verify the required parameter 'patientId' is set
    if (patientId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'patientId' when calling deleteAttachmentUsingDELETE",
        new ApiException(400, "Missing the required parameter 'patientId' when calling deleteAttachmentUsingDELETE"));
    }
    // verify the required parameter 'elementId' is set
    if (elementId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'elementId' when calling deleteAttachmentUsingDELETE",
        new ApiException(400, "Missing the required parameter 'elementId' when calling deleteAttachmentUsingDELETE"));
    }
    // verify the required parameter 'attachmentId' is set
    if (attachmentId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'attachmentId' when calling deleteAttachmentUsingDELETE",
        new ApiException(400, "Missing the required parameter 'attachmentId' when calling deleteAttachmentUsingDELETE"));
    }

    // create path and map variables
    String path = "/orgs/{orgId}/patients/{patientId}/elements/{elementId}/attachments/{attachmentId}".replaceAll("\\{" + "orgId" + "\\}", apiInvoker.escapeString(orgId.toString())).replaceAll("\\{" + "patientId" + "\\}", apiInvoker.escapeString(patientId.toString())).replaceAll("\\{" + "elementId" + "\\}", apiInvoker.escapeString(elementId.toString())).replaceAll("\\{" + "attachmentId" + "\\}", apiInvoker.escapeString(attachmentId.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();
    String[] contentTypes = {
      "application/json"
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
    }

    String[] authNames = new String[] {  };

    try {
      String localVarResponse = apiInvoker.invokeAPI (basePath, path, "DELETE", queryParams, postBody, headerParams, formParams, contentType, authNames);
      if (localVarResponse != null) {
         return (String) ApiInvoker.deserialize(localVarResponse, "", String.class);
      } else {
         return null;
      }
    } catch (ApiException ex) {
       throw ex;
    } catch (InterruptedException ex) {
       throw ex;
    } catch (ExecutionException ex) {
      if (ex.getCause() instanceof VolleyError) {
        VolleyError volleyError = (VolleyError)ex.getCause();
        if (volleyError.networkResponse != null) {
          throw new ApiException(volleyError.networkResponse.statusCode, volleyError.getMessage());
        }
      }
      throw ex;
    } catch (TimeoutException ex) {
      throw ex;
    }
  }

      /**
   * deleteAttachment
   * deleteAttachment
   * @param orgId orgId   * @param patientId patientId   * @param elementId elementId   * @param attachmentId attachmentId
  */
  public void deleteAttachmentUsingDELETE (Long orgId, Long patientId, Long elementId, Integer attachmentId, final Response.Listener<String> responseListener, final Response.ErrorListener errorListener) {
    Object postBody = null;

    // verify the required parameter 'orgId' is set
    if (orgId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'orgId' when calling deleteAttachmentUsingDELETE",
        new ApiException(400, "Missing the required parameter 'orgId' when calling deleteAttachmentUsingDELETE"));
    }
    // verify the required parameter 'patientId' is set
    if (patientId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'patientId' when calling deleteAttachmentUsingDELETE",
        new ApiException(400, "Missing the required parameter 'patientId' when calling deleteAttachmentUsingDELETE"));
    }
    // verify the required parameter 'elementId' is set
    if (elementId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'elementId' when calling deleteAttachmentUsingDELETE",
        new ApiException(400, "Missing the required parameter 'elementId' when calling deleteAttachmentUsingDELETE"));
    }
    // verify the required parameter 'attachmentId' is set
    if (attachmentId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'attachmentId' when calling deleteAttachmentUsingDELETE",
        new ApiException(400, "Missing the required parameter 'attachmentId' when calling deleteAttachmentUsingDELETE"));
    }

    // create path and map variables
    String path = "/orgs/{orgId}/patients/{patientId}/elements/{elementId}/attachments/{attachmentId}".replaceAll("\\{format\\}","json").replaceAll("\\{" + "orgId" + "\\}", apiInvoker.escapeString(orgId.toString())).replaceAll("\\{" + "patientId" + "\\}", apiInvoker.escapeString(patientId.toString())).replaceAll("\\{" + "elementId" + "\\}", apiInvoker.escapeString(elementId.toString())).replaceAll("\\{" + "attachmentId" + "\\}", apiInvoker.escapeString(attachmentId.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();



    String[] contentTypes = {
      "application/json"
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      

      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
          }

    String[] authNames = new String[] {  };

    try {
      apiInvoker.invokeAPI(basePath, path, "DELETE", queryParams, postBody, headerParams, formParams, contentType, authNames,
        new Response.Listener<String>() {
          @Override
          public void onResponse(String localVarResponse) {
            try {
              responseListener.onResponse((String) ApiInvoker.deserialize(localVarResponse,  "", String.class));
            } catch (ApiException exception) {
               errorListener.onErrorResponse(new VolleyError(exception));
            }
          }
      }, new Response.ErrorListener() {
          @Override
          public void onErrorResponse(VolleyError error) {
            errorListener.onErrorResponse(error);
          }
      });
    } catch (ApiException ex) {
      errorListener.onErrorResponse(new VolleyError(ex));
    }
  }
  /**
  * listAttachments
  * listAttachments
   * @param elementId elementId
   * @return String
  */
  public String listAttachmentsUsingGET (Long elementId) throws TimeoutException, ExecutionException, InterruptedException, ApiException {
    Object postBody = null;
    // verify the required parameter 'elementId' is set
    if (elementId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'elementId' when calling listAttachmentsUsingGET",
        new ApiException(400, "Missing the required parameter 'elementId' when calling listAttachmentsUsingGET"));
    }

    // create path and map variables
    String path = "/orgs/{orgId}/patients/{patientId}/elements/{elementId}/attachments".replaceAll("\\{" + "elementId" + "\\}", apiInvoker.escapeString(elementId.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();
    String[] contentTypes = {
      "application/json"
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
    }

    String[] authNames = new String[] {  };

    try {
      String localVarResponse = apiInvoker.invokeAPI (basePath, path, "GET", queryParams, postBody, headerParams, formParams, contentType, authNames);
      if (localVarResponse != null) {
         return (String) ApiInvoker.deserialize(localVarResponse, "", String.class);
      } else {
         return null;
      }
    } catch (ApiException ex) {
       throw ex;
    } catch (InterruptedException ex) {
       throw ex;
    } catch (ExecutionException ex) {
      if (ex.getCause() instanceof VolleyError) {
        VolleyError volleyError = (VolleyError)ex.getCause();
        if (volleyError.networkResponse != null) {
          throw new ApiException(volleyError.networkResponse.statusCode, volleyError.getMessage());
        }
      }
      throw ex;
    } catch (TimeoutException ex) {
      throw ex;
    }
  }

      /**
   * listAttachments
   * listAttachments
   * @param elementId elementId
  */
  public void listAttachmentsUsingGET (Long elementId, final Response.Listener<String> responseListener, final Response.ErrorListener errorListener) {
    Object postBody = null;

    // verify the required parameter 'elementId' is set
    if (elementId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'elementId' when calling listAttachmentsUsingGET",
        new ApiException(400, "Missing the required parameter 'elementId' when calling listAttachmentsUsingGET"));
    }

    // create path and map variables
    String path = "/orgs/{orgId}/patients/{patientId}/elements/{elementId}/attachments".replaceAll("\\{format\\}","json").replaceAll("\\{" + "elementId" + "\\}", apiInvoker.escapeString(elementId.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();



    String[] contentTypes = {
      "application/json"
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      

      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
          }

    String[] authNames = new String[] {  };

    try {
      apiInvoker.invokeAPI(basePath, path, "GET", queryParams, postBody, headerParams, formParams, contentType, authNames,
        new Response.Listener<String>() {
          @Override
          public void onResponse(String localVarResponse) {
            try {
              responseListener.onResponse((String) ApiInvoker.deserialize(localVarResponse,  "", String.class));
            } catch (ApiException exception) {
               errorListener.onErrorResponse(new VolleyError(exception));
            }
          }
      }, new Response.ErrorListener() {
          @Override
          public void onErrorResponse(VolleyError error) {
            errorListener.onErrorResponse(error);
          }
      });
    } catch (ApiException ex) {
      errorListener.onErrorResponse(new VolleyError(ex));
    }
  }
  /**
  * showAttachmentFile2
  * showAttachmentFile2
   * @param orgId orgId
   * @param elementId elementId
   * @param attachmentId attachmentId
   * @return List<byte[]>
  */
  public List<byte[]> showAttachmentFile2UsingGET (Long orgId, Long elementId, Integer attachmentId) throws TimeoutException, ExecutionException, InterruptedException, ApiException {
    Object postBody = null;
    // verify the required parameter 'orgId' is set
    if (orgId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'orgId' when calling showAttachmentFile2UsingGET",
        new ApiException(400, "Missing the required parameter 'orgId' when calling showAttachmentFile2UsingGET"));
    }
    // verify the required parameter 'elementId' is set
    if (elementId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'elementId' when calling showAttachmentFile2UsingGET",
        new ApiException(400, "Missing the required parameter 'elementId' when calling showAttachmentFile2UsingGET"));
    }
    // verify the required parameter 'attachmentId' is set
    if (attachmentId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'attachmentId' when calling showAttachmentFile2UsingGET",
        new ApiException(400, "Missing the required parameter 'attachmentId' when calling showAttachmentFile2UsingGET"));
    }

    // create path and map variables
    String path = "/orgs/{orgId}/patients/{patientId}/elements/{elementId}/attachments/{attachmentId}/file/{fileName}".replaceAll("\\{" + "orgId" + "\\}", apiInvoker.escapeString(orgId.toString())).replaceAll("\\{" + "elementId" + "\\}", apiInvoker.escapeString(elementId.toString())).replaceAll("\\{" + "attachmentId" + "\\}", apiInvoker.escapeString(attachmentId.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();
    String[] contentTypes = {
      "application/json"
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
    }

    String[] authNames = new String[] {  };

    try {
      String localVarResponse = apiInvoker.invokeAPI (basePath, path, "GET", queryParams, postBody, headerParams, formParams, contentType, authNames);
      if (localVarResponse != null) {
         return (List<byte[]>) ApiInvoker.deserialize(localVarResponse, "array", byte[].class);
      } else {
         return null;
      }
    } catch (ApiException ex) {
       throw ex;
    } catch (InterruptedException ex) {
       throw ex;
    } catch (ExecutionException ex) {
      if (ex.getCause() instanceof VolleyError) {
        VolleyError volleyError = (VolleyError)ex.getCause();
        if (volleyError.networkResponse != null) {
          throw new ApiException(volleyError.networkResponse.statusCode, volleyError.getMessage());
        }
      }
      throw ex;
    } catch (TimeoutException ex) {
      throw ex;
    }
  }

      /**
   * showAttachmentFile2
   * showAttachmentFile2
   * @param orgId orgId   * @param elementId elementId   * @param attachmentId attachmentId
  */
  public void showAttachmentFile2UsingGET (Long orgId, Long elementId, Integer attachmentId, final Response.Listener<List<byte[]>> responseListener, final Response.ErrorListener errorListener) {
    Object postBody = null;

    // verify the required parameter 'orgId' is set
    if (orgId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'orgId' when calling showAttachmentFile2UsingGET",
        new ApiException(400, "Missing the required parameter 'orgId' when calling showAttachmentFile2UsingGET"));
    }
    // verify the required parameter 'elementId' is set
    if (elementId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'elementId' when calling showAttachmentFile2UsingGET",
        new ApiException(400, "Missing the required parameter 'elementId' when calling showAttachmentFile2UsingGET"));
    }
    // verify the required parameter 'attachmentId' is set
    if (attachmentId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'attachmentId' when calling showAttachmentFile2UsingGET",
        new ApiException(400, "Missing the required parameter 'attachmentId' when calling showAttachmentFile2UsingGET"));
    }

    // create path and map variables
    String path = "/orgs/{orgId}/patients/{patientId}/elements/{elementId}/attachments/{attachmentId}/file/{fileName}".replaceAll("\\{format\\}","json").replaceAll("\\{" + "orgId" + "\\}", apiInvoker.escapeString(orgId.toString())).replaceAll("\\{" + "elementId" + "\\}", apiInvoker.escapeString(elementId.toString())).replaceAll("\\{" + "attachmentId" + "\\}", apiInvoker.escapeString(attachmentId.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();



    String[] contentTypes = {
      "application/json"
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      

      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
          }

    String[] authNames = new String[] {  };

    try {
      apiInvoker.invokeAPI(basePath, path, "GET", queryParams, postBody, headerParams, formParams, contentType, authNames,
        new Response.Listener<String>() {
          @Override
          public void onResponse(String localVarResponse) {
            try {
              responseListener.onResponse((List<byte[]>) ApiInvoker.deserialize(localVarResponse,  "array", byte[].class));
            } catch (ApiException exception) {
               errorListener.onErrorResponse(new VolleyError(exception));
            }
          }
      }, new Response.ErrorListener() {
          @Override
          public void onErrorResponse(VolleyError error) {
            errorListener.onErrorResponse(error);
          }
      });
    } catch (ApiException ex) {
      errorListener.onErrorResponse(new VolleyError(ex));
    }
  }
  /**
  * showAttachmentFile
  * showAttachmentFile
   * @param orgId orgId
   * @param elementId elementId
   * @param attachmentId attachmentId
   * @return List<byte[]>
  */
  public List<byte[]> showAttachmentFileUsingGET (Long orgId, Long elementId, Integer attachmentId) throws TimeoutException, ExecutionException, InterruptedException, ApiException {
    Object postBody = null;
    // verify the required parameter 'orgId' is set
    if (orgId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'orgId' when calling showAttachmentFileUsingGET",
        new ApiException(400, "Missing the required parameter 'orgId' when calling showAttachmentFileUsingGET"));
    }
    // verify the required parameter 'elementId' is set
    if (elementId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'elementId' when calling showAttachmentFileUsingGET",
        new ApiException(400, "Missing the required parameter 'elementId' when calling showAttachmentFileUsingGET"));
    }
    // verify the required parameter 'attachmentId' is set
    if (attachmentId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'attachmentId' when calling showAttachmentFileUsingGET",
        new ApiException(400, "Missing the required parameter 'attachmentId' when calling showAttachmentFileUsingGET"));
    }

    // create path and map variables
    String path = "/orgs/{orgId}/patients/{patientId}/elements/{elementId}/attachments/{attachmentId}/file".replaceAll("\\{" + "orgId" + "\\}", apiInvoker.escapeString(orgId.toString())).replaceAll("\\{" + "elementId" + "\\}", apiInvoker.escapeString(elementId.toString())).replaceAll("\\{" + "attachmentId" + "\\}", apiInvoker.escapeString(attachmentId.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();
    String[] contentTypes = {
      "application/json"
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
    }

    String[] authNames = new String[] {  };

    try {
      String localVarResponse = apiInvoker.invokeAPI (basePath, path, "GET", queryParams, postBody, headerParams, formParams, contentType, authNames);
      if (localVarResponse != null) {
         return (List<byte[]>) ApiInvoker.deserialize(localVarResponse, "array", byte[].class);
      } else {
         return null;
      }
    } catch (ApiException ex) {
       throw ex;
    } catch (InterruptedException ex) {
       throw ex;
    } catch (ExecutionException ex) {
      if (ex.getCause() instanceof VolleyError) {
        VolleyError volleyError = (VolleyError)ex.getCause();
        if (volleyError.networkResponse != null) {
          throw new ApiException(volleyError.networkResponse.statusCode, volleyError.getMessage());
        }
      }
      throw ex;
    } catch (TimeoutException ex) {
      throw ex;
    }
  }

      /**
   * showAttachmentFile
   * showAttachmentFile
   * @param orgId orgId   * @param elementId elementId   * @param attachmentId attachmentId
  */
  public void showAttachmentFileUsingGET (Long orgId, Long elementId, Integer attachmentId, final Response.Listener<List<byte[]>> responseListener, final Response.ErrorListener errorListener) {
    Object postBody = null;

    // verify the required parameter 'orgId' is set
    if (orgId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'orgId' when calling showAttachmentFileUsingGET",
        new ApiException(400, "Missing the required parameter 'orgId' when calling showAttachmentFileUsingGET"));
    }
    // verify the required parameter 'elementId' is set
    if (elementId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'elementId' when calling showAttachmentFileUsingGET",
        new ApiException(400, "Missing the required parameter 'elementId' when calling showAttachmentFileUsingGET"));
    }
    // verify the required parameter 'attachmentId' is set
    if (attachmentId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'attachmentId' when calling showAttachmentFileUsingGET",
        new ApiException(400, "Missing the required parameter 'attachmentId' when calling showAttachmentFileUsingGET"));
    }

    // create path and map variables
    String path = "/orgs/{orgId}/patients/{patientId}/elements/{elementId}/attachments/{attachmentId}/file".replaceAll("\\{format\\}","json").replaceAll("\\{" + "orgId" + "\\}", apiInvoker.escapeString(orgId.toString())).replaceAll("\\{" + "elementId" + "\\}", apiInvoker.escapeString(elementId.toString())).replaceAll("\\{" + "attachmentId" + "\\}", apiInvoker.escapeString(attachmentId.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();



    String[] contentTypes = {
      "application/json"
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      

      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
          }

    String[] authNames = new String[] {  };

    try {
      apiInvoker.invokeAPI(basePath, path, "GET", queryParams, postBody, headerParams, formParams, contentType, authNames,
        new Response.Listener<String>() {
          @Override
          public void onResponse(String localVarResponse) {
            try {
              responseListener.onResponse((List<byte[]>) ApiInvoker.deserialize(localVarResponse,  "array", byte[].class));
            } catch (ApiException exception) {
               errorListener.onErrorResponse(new VolleyError(exception));
            }
          }
      }, new Response.ErrorListener() {
          @Override
          public void onErrorResponse(VolleyError error) {
            errorListener.onErrorResponse(error);
          }
      });
    } catch (ApiException ex) {
      errorListener.onErrorResponse(new VolleyError(ex));
    }
  }
  /**
  * showAttachment
  * showAttachment
   * @param elementId elId
   * @param attachmentId attachmentId
   * @return String
  */
  public String showAttachmentUsingGET (Long elementId, Integer attachmentId) throws TimeoutException, ExecutionException, InterruptedException, ApiException {
    Object postBody = null;
    // verify the required parameter 'elementId' is set
    if (elementId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'elementId' when calling showAttachmentUsingGET",
        new ApiException(400, "Missing the required parameter 'elementId' when calling showAttachmentUsingGET"));
    }
    // verify the required parameter 'attachmentId' is set
    if (attachmentId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'attachmentId' when calling showAttachmentUsingGET",
        new ApiException(400, "Missing the required parameter 'attachmentId' when calling showAttachmentUsingGET"));
    }

    // create path and map variables
    String path = "/orgs/{orgId}/patients/{patientId}/elements/{elementId}/attachments/{attachmentId}".replaceAll("\\{" + "elementId" + "\\}", apiInvoker.escapeString(elementId.toString())).replaceAll("\\{" + "attachmentId" + "\\}", apiInvoker.escapeString(attachmentId.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();
    String[] contentTypes = {
      "application/json"
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
    }

    String[] authNames = new String[] {  };

    try {
      String localVarResponse = apiInvoker.invokeAPI (basePath, path, "GET", queryParams, postBody, headerParams, formParams, contentType, authNames);
      if (localVarResponse != null) {
         return (String) ApiInvoker.deserialize(localVarResponse, "", String.class);
      } else {
         return null;
      }
    } catch (ApiException ex) {
       throw ex;
    } catch (InterruptedException ex) {
       throw ex;
    } catch (ExecutionException ex) {
      if (ex.getCause() instanceof VolleyError) {
        VolleyError volleyError = (VolleyError)ex.getCause();
        if (volleyError.networkResponse != null) {
          throw new ApiException(volleyError.networkResponse.statusCode, volleyError.getMessage());
        }
      }
      throw ex;
    } catch (TimeoutException ex) {
      throw ex;
    }
  }

      /**
   * showAttachment
   * showAttachment
   * @param elementId elId   * @param attachmentId attachmentId
  */
  public void showAttachmentUsingGET (Long elementId, Integer attachmentId, final Response.Listener<String> responseListener, final Response.ErrorListener errorListener) {
    Object postBody = null;

    // verify the required parameter 'elementId' is set
    if (elementId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'elementId' when calling showAttachmentUsingGET",
        new ApiException(400, "Missing the required parameter 'elementId' when calling showAttachmentUsingGET"));
    }
    // verify the required parameter 'attachmentId' is set
    if (attachmentId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'attachmentId' when calling showAttachmentUsingGET",
        new ApiException(400, "Missing the required parameter 'attachmentId' when calling showAttachmentUsingGET"));
    }

    // create path and map variables
    String path = "/orgs/{orgId}/patients/{patientId}/elements/{elementId}/attachments/{attachmentId}".replaceAll("\\{format\\}","json").replaceAll("\\{" + "elementId" + "\\}", apiInvoker.escapeString(elementId.toString())).replaceAll("\\{" + "attachmentId" + "\\}", apiInvoker.escapeString(attachmentId.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();



    String[] contentTypes = {
      "application/json"
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      

      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
          }

    String[] authNames = new String[] {  };

    try {
      apiInvoker.invokeAPI(basePath, path, "GET", queryParams, postBody, headerParams, formParams, contentType, authNames,
        new Response.Listener<String>() {
          @Override
          public void onResponse(String localVarResponse) {
            try {
              responseListener.onResponse((String) ApiInvoker.deserialize(localVarResponse,  "", String.class));
            } catch (ApiException exception) {
               errorListener.onErrorResponse(new VolleyError(exception));
            }
          }
      }, new Response.ErrorListener() {
          @Override
          public void onErrorResponse(VolleyError error) {
            errorListener.onErrorResponse(error);
          }
      });
    } catch (ApiException ex) {
      errorListener.onErrorResponse(new VolleyError(ex));
    }
  }

}
