/**
 * SMIS2-CORE REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiInvoker;
import io.swagger.client.ApiException;
import io.swagger.client.Pair;

import io.swagger.client.model.*;

import java.util.*;

import com.android.volley.Response;
import com.android.volley.VolleyError;

import org.apache.http.HttpEntity;
import org.apache.http.entity.mime.MultipartEntityBuilder;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.TimeoutException;

public class SorgpatientdoccontrollerApi {
  String basePath = "https://localhost:8080/smis2-core";
  ApiInvoker apiInvoker = ApiInvoker.getInstance();

  public void addHeader(String key, String value) {
    getInvoker().addDefaultHeader(key, value);
  }

  public ApiInvoker getInvoker() {
    return apiInvoker;
  }

  public void setBasePath(String basePath) {
    this.basePath = basePath;
  }

  public String getBasePath() {
    return basePath;
  }


  /**
  * deleteDocument
  * deleteDocument
   * @param orgId orgId
   * @param patientId patientId
   * @param docId docId
   * @return String
  */
  public String deleteDocumentUsingDELETE (Long orgId, Long patientId, Long docId) throws TimeoutException, ExecutionException, InterruptedException, ApiException {
    Object postBody = null;
    // verify the required parameter 'orgId' is set
    if (orgId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'orgId' when calling deleteDocumentUsingDELETE",
        new ApiException(400, "Missing the required parameter 'orgId' when calling deleteDocumentUsingDELETE"));
    }
    // verify the required parameter 'patientId' is set
    if (patientId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'patientId' when calling deleteDocumentUsingDELETE",
        new ApiException(400, "Missing the required parameter 'patientId' when calling deleteDocumentUsingDELETE"));
    }
    // verify the required parameter 'docId' is set
    if (docId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'docId' when calling deleteDocumentUsingDELETE",
        new ApiException(400, "Missing the required parameter 'docId' when calling deleteDocumentUsingDELETE"));
    }

    // create path and map variables
    String path = "/orgs/{orgId}/patients/{patientId}/documents/{docId}".replaceAll("\\{" + "orgId" + "\\}", apiInvoker.escapeString(orgId.toString())).replaceAll("\\{" + "patientId" + "\\}", apiInvoker.escapeString(patientId.toString())).replaceAll("\\{" + "docId" + "\\}", apiInvoker.escapeString(docId.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();
    String[] contentTypes = {
      "application/json"
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
    }

    String[] authNames = new String[] {  };

    try {
      String localVarResponse = apiInvoker.invokeAPI (basePath, path, "DELETE", queryParams, postBody, headerParams, formParams, contentType, authNames);
      if (localVarResponse != null) {
         return (String) ApiInvoker.deserialize(localVarResponse, "", String.class);
      } else {
         return null;
      }
    } catch (ApiException ex) {
       throw ex;
    } catch (InterruptedException ex) {
       throw ex;
    } catch (ExecutionException ex) {
      if (ex.getCause() instanceof VolleyError) {
        VolleyError volleyError = (VolleyError)ex.getCause();
        if (volleyError.networkResponse != null) {
          throw new ApiException(volleyError.networkResponse.statusCode, volleyError.getMessage());
        }
      }
      throw ex;
    } catch (TimeoutException ex) {
      throw ex;
    }
  }

      /**
   * deleteDocument
   * deleteDocument
   * @param orgId orgId   * @param patientId patientId   * @param docId docId
  */
  public void deleteDocumentUsingDELETE (Long orgId, Long patientId, Long docId, final Response.Listener<String> responseListener, final Response.ErrorListener errorListener) {
    Object postBody = null;

    // verify the required parameter 'orgId' is set
    if (orgId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'orgId' when calling deleteDocumentUsingDELETE",
        new ApiException(400, "Missing the required parameter 'orgId' when calling deleteDocumentUsingDELETE"));
    }
    // verify the required parameter 'patientId' is set
    if (patientId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'patientId' when calling deleteDocumentUsingDELETE",
        new ApiException(400, "Missing the required parameter 'patientId' when calling deleteDocumentUsingDELETE"));
    }
    // verify the required parameter 'docId' is set
    if (docId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'docId' when calling deleteDocumentUsingDELETE",
        new ApiException(400, "Missing the required parameter 'docId' when calling deleteDocumentUsingDELETE"));
    }

    // create path and map variables
    String path = "/orgs/{orgId}/patients/{patientId}/documents/{docId}".replaceAll("\\{format\\}","json").replaceAll("\\{" + "orgId" + "\\}", apiInvoker.escapeString(orgId.toString())).replaceAll("\\{" + "patientId" + "\\}", apiInvoker.escapeString(patientId.toString())).replaceAll("\\{" + "docId" + "\\}", apiInvoker.escapeString(docId.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();



    String[] contentTypes = {
      "application/json"
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      

      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
          }

    String[] authNames = new String[] {  };

    try {
      apiInvoker.invokeAPI(basePath, path, "DELETE", queryParams, postBody, headerParams, formParams, contentType, authNames,
        new Response.Listener<String>() {
          @Override
          public void onResponse(String localVarResponse) {
            try {
              responseListener.onResponse((String) ApiInvoker.deserialize(localVarResponse,  "", String.class));
            } catch (ApiException exception) {
               errorListener.onErrorResponse(new VolleyError(exception));
            }
          }
      }, new Response.ErrorListener() {
          @Override
          public void onErrorResponse(VolleyError error) {
            errorListener.onErrorResponse(error);
          }
      });
    } catch (ApiException ex) {
      errorListener.onErrorResponse(new VolleyError(ex));
    }
  }
  /**
  * listDocuments
  * listDocuments
   * @param orgId orgId
   * @param patientId patientId
   * @return String
  */
  public String listDocumentsUsingDELETE (Long orgId, Long patientId) throws TimeoutException, ExecutionException, InterruptedException, ApiException {
    Object postBody = null;
    // verify the required parameter 'orgId' is set
    if (orgId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'orgId' when calling listDocumentsUsingDELETE",
        new ApiException(400, "Missing the required parameter 'orgId' when calling listDocumentsUsingDELETE"));
    }
    // verify the required parameter 'patientId' is set
    if (patientId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'patientId' when calling listDocumentsUsingDELETE",
        new ApiException(400, "Missing the required parameter 'patientId' when calling listDocumentsUsingDELETE"));
    }

    // create path and map variables
    String path = "/orgs/{orgId}/patients/{patientId}/documents".replaceAll("\\{" + "orgId" + "\\}", apiInvoker.escapeString(orgId.toString())).replaceAll("\\{" + "patientId" + "\\}", apiInvoker.escapeString(patientId.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();
    String[] contentTypes = {
      "application/json"
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
    }

    String[] authNames = new String[] {  };

    try {
      String localVarResponse = apiInvoker.invokeAPI (basePath, path, "DELETE", queryParams, postBody, headerParams, formParams, contentType, authNames);
      if (localVarResponse != null) {
         return (String) ApiInvoker.deserialize(localVarResponse, "", String.class);
      } else {
         return null;
      }
    } catch (ApiException ex) {
       throw ex;
    } catch (InterruptedException ex) {
       throw ex;
    } catch (ExecutionException ex) {
      if (ex.getCause() instanceof VolleyError) {
        VolleyError volleyError = (VolleyError)ex.getCause();
        if (volleyError.networkResponse != null) {
          throw new ApiException(volleyError.networkResponse.statusCode, volleyError.getMessage());
        }
      }
      throw ex;
    } catch (TimeoutException ex) {
      throw ex;
    }
  }

      /**
   * listDocuments
   * listDocuments
   * @param orgId orgId   * @param patientId patientId
  */
  public void listDocumentsUsingDELETE (Long orgId, Long patientId, final Response.Listener<String> responseListener, final Response.ErrorListener errorListener) {
    Object postBody = null;

    // verify the required parameter 'orgId' is set
    if (orgId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'orgId' when calling listDocumentsUsingDELETE",
        new ApiException(400, "Missing the required parameter 'orgId' when calling listDocumentsUsingDELETE"));
    }
    // verify the required parameter 'patientId' is set
    if (patientId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'patientId' when calling listDocumentsUsingDELETE",
        new ApiException(400, "Missing the required parameter 'patientId' when calling listDocumentsUsingDELETE"));
    }

    // create path and map variables
    String path = "/orgs/{orgId}/patients/{patientId}/documents".replaceAll("\\{format\\}","json").replaceAll("\\{" + "orgId" + "\\}", apiInvoker.escapeString(orgId.toString())).replaceAll("\\{" + "patientId" + "\\}", apiInvoker.escapeString(patientId.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();



    String[] contentTypes = {
      "application/json"
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      

      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
          }

    String[] authNames = new String[] {  };

    try {
      apiInvoker.invokeAPI(basePath, path, "DELETE", queryParams, postBody, headerParams, formParams, contentType, authNames,
        new Response.Listener<String>() {
          @Override
          public void onResponse(String localVarResponse) {
            try {
              responseListener.onResponse((String) ApiInvoker.deserialize(localVarResponse,  "", String.class));
            } catch (ApiException exception) {
               errorListener.onErrorResponse(new VolleyError(exception));
            }
          }
      }, new Response.ErrorListener() {
          @Override
          public void onErrorResponse(VolleyError error) {
            errorListener.onErrorResponse(error);
          }
      });
    } catch (ApiException ex) {
      errorListener.onErrorResponse(new VolleyError(ex));
    }
  }
  /**
  * listDocuments
  * listDocuments
   * @param orgId orgId
   * @param patientId patientId
   * @return String
  */
  public String listDocumentsUsingGET (Long orgId, Long patientId) throws TimeoutException, ExecutionException, InterruptedException, ApiException {
    Object postBody = null;
    // verify the required parameter 'orgId' is set
    if (orgId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'orgId' when calling listDocumentsUsingGET",
        new ApiException(400, "Missing the required parameter 'orgId' when calling listDocumentsUsingGET"));
    }
    // verify the required parameter 'patientId' is set
    if (patientId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'patientId' when calling listDocumentsUsingGET",
        new ApiException(400, "Missing the required parameter 'patientId' when calling listDocumentsUsingGET"));
    }

    // create path and map variables
    String path = "/orgs/{orgId}/patients/{patientId}/documents".replaceAll("\\{" + "orgId" + "\\}", apiInvoker.escapeString(orgId.toString())).replaceAll("\\{" + "patientId" + "\\}", apiInvoker.escapeString(patientId.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();
    String[] contentTypes = {
      "application/json"
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
    }

    String[] authNames = new String[] {  };

    try {
      String localVarResponse = apiInvoker.invokeAPI (basePath, path, "GET", queryParams, postBody, headerParams, formParams, contentType, authNames);
      if (localVarResponse != null) {
         return (String) ApiInvoker.deserialize(localVarResponse, "", String.class);
      } else {
         return null;
      }
    } catch (ApiException ex) {
       throw ex;
    } catch (InterruptedException ex) {
       throw ex;
    } catch (ExecutionException ex) {
      if (ex.getCause() instanceof VolleyError) {
        VolleyError volleyError = (VolleyError)ex.getCause();
        if (volleyError.networkResponse != null) {
          throw new ApiException(volleyError.networkResponse.statusCode, volleyError.getMessage());
        }
      }
      throw ex;
    } catch (TimeoutException ex) {
      throw ex;
    }
  }

      /**
   * listDocuments
   * listDocuments
   * @param orgId orgId   * @param patientId patientId
  */
  public void listDocumentsUsingGET (Long orgId, Long patientId, final Response.Listener<String> responseListener, final Response.ErrorListener errorListener) {
    Object postBody = null;

    // verify the required parameter 'orgId' is set
    if (orgId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'orgId' when calling listDocumentsUsingGET",
        new ApiException(400, "Missing the required parameter 'orgId' when calling listDocumentsUsingGET"));
    }
    // verify the required parameter 'patientId' is set
    if (patientId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'patientId' when calling listDocumentsUsingGET",
        new ApiException(400, "Missing the required parameter 'patientId' when calling listDocumentsUsingGET"));
    }

    // create path and map variables
    String path = "/orgs/{orgId}/patients/{patientId}/documents".replaceAll("\\{format\\}","json").replaceAll("\\{" + "orgId" + "\\}", apiInvoker.escapeString(orgId.toString())).replaceAll("\\{" + "patientId" + "\\}", apiInvoker.escapeString(patientId.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();



    String[] contentTypes = {
      "application/json"
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      

      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
          }

    String[] authNames = new String[] {  };

    try {
      apiInvoker.invokeAPI(basePath, path, "GET", queryParams, postBody, headerParams, formParams, contentType, authNames,
        new Response.Listener<String>() {
          @Override
          public void onResponse(String localVarResponse) {
            try {
              responseListener.onResponse((String) ApiInvoker.deserialize(localVarResponse,  "", String.class));
            } catch (ApiException exception) {
               errorListener.onErrorResponse(new VolleyError(exception));
            }
          }
      }, new Response.ErrorListener() {
          @Override
          public void onErrorResponse(VolleyError error) {
            errorListener.onErrorResponse(error);
          }
      });
    } catch (ApiException ex) {
      errorListener.onErrorResponse(new VolleyError(ex));
    }
  }
  /**
  * listDocuments
  * listDocuments
   * @param orgId orgId
   * @param patientId patientId
   * @return String
  */
  public String listDocumentsUsingOPTIONS (Long orgId, Long patientId) throws TimeoutException, ExecutionException, InterruptedException, ApiException {
    Object postBody = null;
    // verify the required parameter 'orgId' is set
    if (orgId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'orgId' when calling listDocumentsUsingOPTIONS",
        new ApiException(400, "Missing the required parameter 'orgId' when calling listDocumentsUsingOPTIONS"));
    }
    // verify the required parameter 'patientId' is set
    if (patientId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'patientId' when calling listDocumentsUsingOPTIONS",
        new ApiException(400, "Missing the required parameter 'patientId' when calling listDocumentsUsingOPTIONS"));
    }

    // create path and map variables
    String path = "/orgs/{orgId}/patients/{patientId}/documents".replaceAll("\\{" + "orgId" + "\\}", apiInvoker.escapeString(orgId.toString())).replaceAll("\\{" + "patientId" + "\\}", apiInvoker.escapeString(patientId.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();
    String[] contentTypes = {
      "application/json"
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
    }

    String[] authNames = new String[] {  };

    try {
      String localVarResponse = apiInvoker.invokeAPI (basePath, path, "OPTIONS", queryParams, postBody, headerParams, formParams, contentType, authNames);
      if (localVarResponse != null) {
         return (String) ApiInvoker.deserialize(localVarResponse, "", String.class);
      } else {
         return null;
      }
    } catch (ApiException ex) {
       throw ex;
    } catch (InterruptedException ex) {
       throw ex;
    } catch (ExecutionException ex) {
      if (ex.getCause() instanceof VolleyError) {
        VolleyError volleyError = (VolleyError)ex.getCause();
        if (volleyError.networkResponse != null) {
          throw new ApiException(volleyError.networkResponse.statusCode, volleyError.getMessage());
        }
      }
      throw ex;
    } catch (TimeoutException ex) {
      throw ex;
    }
  }

      /**
   * listDocuments
   * listDocuments
   * @param orgId orgId   * @param patientId patientId
  */
  public void listDocumentsUsingOPTIONS (Long orgId, Long patientId, final Response.Listener<String> responseListener, final Response.ErrorListener errorListener) {
    Object postBody = null;

    // verify the required parameter 'orgId' is set
    if (orgId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'orgId' when calling listDocumentsUsingOPTIONS",
        new ApiException(400, "Missing the required parameter 'orgId' when calling listDocumentsUsingOPTIONS"));
    }
    // verify the required parameter 'patientId' is set
    if (patientId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'patientId' when calling listDocumentsUsingOPTIONS",
        new ApiException(400, "Missing the required parameter 'patientId' when calling listDocumentsUsingOPTIONS"));
    }

    // create path and map variables
    String path = "/orgs/{orgId}/patients/{patientId}/documents".replaceAll("\\{format\\}","json").replaceAll("\\{" + "orgId" + "\\}", apiInvoker.escapeString(orgId.toString())).replaceAll("\\{" + "patientId" + "\\}", apiInvoker.escapeString(patientId.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();



    String[] contentTypes = {
      "application/json"
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      

      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
          }

    String[] authNames = new String[] {  };

    try {
      apiInvoker.invokeAPI(basePath, path, "OPTIONS", queryParams, postBody, headerParams, formParams, contentType, authNames,
        new Response.Listener<String>() {
          @Override
          public void onResponse(String localVarResponse) {
            try {
              responseListener.onResponse((String) ApiInvoker.deserialize(localVarResponse,  "", String.class));
            } catch (ApiException exception) {
               errorListener.onErrorResponse(new VolleyError(exception));
            }
          }
      }, new Response.ErrorListener() {
          @Override
          public void onErrorResponse(VolleyError error) {
            errorListener.onErrorResponse(error);
          }
      });
    } catch (ApiException ex) {
      errorListener.onErrorResponse(new VolleyError(ex));
    }
  }
  /**
  * listDocuments
  * listDocuments
   * @param orgId orgId
   * @param patientId patientId
   * @return String
  */
  public String listDocumentsUsingPATCH (Long orgId, Long patientId) throws TimeoutException, ExecutionException, InterruptedException, ApiException {
    Object postBody = null;
    // verify the required parameter 'orgId' is set
    if (orgId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'orgId' when calling listDocumentsUsingPATCH",
        new ApiException(400, "Missing the required parameter 'orgId' when calling listDocumentsUsingPATCH"));
    }
    // verify the required parameter 'patientId' is set
    if (patientId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'patientId' when calling listDocumentsUsingPATCH",
        new ApiException(400, "Missing the required parameter 'patientId' when calling listDocumentsUsingPATCH"));
    }

    // create path and map variables
    String path = "/orgs/{orgId}/patients/{patientId}/documents".replaceAll("\\{" + "orgId" + "\\}", apiInvoker.escapeString(orgId.toString())).replaceAll("\\{" + "patientId" + "\\}", apiInvoker.escapeString(patientId.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();
    String[] contentTypes = {
      "application/json"
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
    }

    String[] authNames = new String[] {  };

    try {
      String localVarResponse = apiInvoker.invokeAPI (basePath, path, "PATCH", queryParams, postBody, headerParams, formParams, contentType, authNames);
      if (localVarResponse != null) {
         return (String) ApiInvoker.deserialize(localVarResponse, "", String.class);
      } else {
         return null;
      }
    } catch (ApiException ex) {
       throw ex;
    } catch (InterruptedException ex) {
       throw ex;
    } catch (ExecutionException ex) {
      if (ex.getCause() instanceof VolleyError) {
        VolleyError volleyError = (VolleyError)ex.getCause();
        if (volleyError.networkResponse != null) {
          throw new ApiException(volleyError.networkResponse.statusCode, volleyError.getMessage());
        }
      }
      throw ex;
    } catch (TimeoutException ex) {
      throw ex;
    }
  }

      /**
   * listDocuments
   * listDocuments
   * @param orgId orgId   * @param patientId patientId
  */
  public void listDocumentsUsingPATCH (Long orgId, Long patientId, final Response.Listener<String> responseListener, final Response.ErrorListener errorListener) {
    Object postBody = null;

    // verify the required parameter 'orgId' is set
    if (orgId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'orgId' when calling listDocumentsUsingPATCH",
        new ApiException(400, "Missing the required parameter 'orgId' when calling listDocumentsUsingPATCH"));
    }
    // verify the required parameter 'patientId' is set
    if (patientId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'patientId' when calling listDocumentsUsingPATCH",
        new ApiException(400, "Missing the required parameter 'patientId' when calling listDocumentsUsingPATCH"));
    }

    // create path and map variables
    String path = "/orgs/{orgId}/patients/{patientId}/documents".replaceAll("\\{format\\}","json").replaceAll("\\{" + "orgId" + "\\}", apiInvoker.escapeString(orgId.toString())).replaceAll("\\{" + "patientId" + "\\}", apiInvoker.escapeString(patientId.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();



    String[] contentTypes = {
      "application/json"
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      

      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
          }

    String[] authNames = new String[] {  };

    try {
      apiInvoker.invokeAPI(basePath, path, "PATCH", queryParams, postBody, headerParams, formParams, contentType, authNames,
        new Response.Listener<String>() {
          @Override
          public void onResponse(String localVarResponse) {
            try {
              responseListener.onResponse((String) ApiInvoker.deserialize(localVarResponse,  "", String.class));
            } catch (ApiException exception) {
               errorListener.onErrorResponse(new VolleyError(exception));
            }
          }
      }, new Response.ErrorListener() {
          @Override
          public void onErrorResponse(VolleyError error) {
            errorListener.onErrorResponse(error);
          }
      });
    } catch (ApiException ex) {
      errorListener.onErrorResponse(new VolleyError(ex));
    }
  }
  /**
  * listDocuments
  * listDocuments
   * @param orgId orgId
   * @param patientId patientId
   * @return String
  */
  public String listDocumentsUsingPUT (Long orgId, Long patientId) throws TimeoutException, ExecutionException, InterruptedException, ApiException {
    Object postBody = null;
    // verify the required parameter 'orgId' is set
    if (orgId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'orgId' when calling listDocumentsUsingPUT",
        new ApiException(400, "Missing the required parameter 'orgId' when calling listDocumentsUsingPUT"));
    }
    // verify the required parameter 'patientId' is set
    if (patientId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'patientId' when calling listDocumentsUsingPUT",
        new ApiException(400, "Missing the required parameter 'patientId' when calling listDocumentsUsingPUT"));
    }

    // create path and map variables
    String path = "/orgs/{orgId}/patients/{patientId}/documents".replaceAll("\\{" + "orgId" + "\\}", apiInvoker.escapeString(orgId.toString())).replaceAll("\\{" + "patientId" + "\\}", apiInvoker.escapeString(patientId.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();
    String[] contentTypes = {
      "application/json"
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
    }

    String[] authNames = new String[] {  };

    try {
      String localVarResponse = apiInvoker.invokeAPI (basePath, path, "PUT", queryParams, postBody, headerParams, formParams, contentType, authNames);
      if (localVarResponse != null) {
         return (String) ApiInvoker.deserialize(localVarResponse, "", String.class);
      } else {
         return null;
      }
    } catch (ApiException ex) {
       throw ex;
    } catch (InterruptedException ex) {
       throw ex;
    } catch (ExecutionException ex) {
      if (ex.getCause() instanceof VolleyError) {
        VolleyError volleyError = (VolleyError)ex.getCause();
        if (volleyError.networkResponse != null) {
          throw new ApiException(volleyError.networkResponse.statusCode, volleyError.getMessage());
        }
      }
      throw ex;
    } catch (TimeoutException ex) {
      throw ex;
    }
  }

      /**
   * listDocuments
   * listDocuments
   * @param orgId orgId   * @param patientId patientId
  */
  public void listDocumentsUsingPUT (Long orgId, Long patientId, final Response.Listener<String> responseListener, final Response.ErrorListener errorListener) {
    Object postBody = null;

    // verify the required parameter 'orgId' is set
    if (orgId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'orgId' when calling listDocumentsUsingPUT",
        new ApiException(400, "Missing the required parameter 'orgId' when calling listDocumentsUsingPUT"));
    }
    // verify the required parameter 'patientId' is set
    if (patientId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'patientId' when calling listDocumentsUsingPUT",
        new ApiException(400, "Missing the required parameter 'patientId' when calling listDocumentsUsingPUT"));
    }

    // create path and map variables
    String path = "/orgs/{orgId}/patients/{patientId}/documents".replaceAll("\\{format\\}","json").replaceAll("\\{" + "orgId" + "\\}", apiInvoker.escapeString(orgId.toString())).replaceAll("\\{" + "patientId" + "\\}", apiInvoker.escapeString(patientId.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();



    String[] contentTypes = {
      "application/json"
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      

      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
          }

    String[] authNames = new String[] {  };

    try {
      apiInvoker.invokeAPI(basePath, path, "PUT", queryParams, postBody, headerParams, formParams, contentType, authNames,
        new Response.Listener<String>() {
          @Override
          public void onResponse(String localVarResponse) {
            try {
              responseListener.onResponse((String) ApiInvoker.deserialize(localVarResponse,  "", String.class));
            } catch (ApiException exception) {
               errorListener.onErrorResponse(new VolleyError(exception));
            }
          }
      }, new Response.ErrorListener() {
          @Override
          public void onErrorResponse(VolleyError error) {
            errorListener.onErrorResponse(error);
          }
      });
    } catch (ApiException ex) {
      errorListener.onErrorResponse(new VolleyError(ex));
    }
  }
  /**
  * showDocumentFile2
  * showDocumentFile2
   * @param orgId orgId
   * @param patientId patientId
   * @param docId docId
   * @return List<byte[]>
  */
  public List<byte[]> showDocumentFile2UsingGET (Long orgId, Long patientId, Long docId) throws TimeoutException, ExecutionException, InterruptedException, ApiException {
    Object postBody = null;
    // verify the required parameter 'orgId' is set
    if (orgId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'orgId' when calling showDocumentFile2UsingGET",
        new ApiException(400, "Missing the required parameter 'orgId' when calling showDocumentFile2UsingGET"));
    }
    // verify the required parameter 'patientId' is set
    if (patientId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'patientId' when calling showDocumentFile2UsingGET",
        new ApiException(400, "Missing the required parameter 'patientId' when calling showDocumentFile2UsingGET"));
    }
    // verify the required parameter 'docId' is set
    if (docId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'docId' when calling showDocumentFile2UsingGET",
        new ApiException(400, "Missing the required parameter 'docId' when calling showDocumentFile2UsingGET"));
    }

    // create path and map variables
    String path = "/orgs/{orgId}/patients/{patientId}/documents/{docId}/file/{fileName}".replaceAll("\\{" + "orgId" + "\\}", apiInvoker.escapeString(orgId.toString())).replaceAll("\\{" + "patientId" + "\\}", apiInvoker.escapeString(patientId.toString())).replaceAll("\\{" + "docId" + "\\}", apiInvoker.escapeString(docId.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();
    String[] contentTypes = {
      "application/json"
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
    }

    String[] authNames = new String[] {  };

    try {
      String localVarResponse = apiInvoker.invokeAPI (basePath, path, "GET", queryParams, postBody, headerParams, formParams, contentType, authNames);
      if (localVarResponse != null) {
         return (List<byte[]>) ApiInvoker.deserialize(localVarResponse, "array", byte[].class);
      } else {
         return null;
      }
    } catch (ApiException ex) {
       throw ex;
    } catch (InterruptedException ex) {
       throw ex;
    } catch (ExecutionException ex) {
      if (ex.getCause() instanceof VolleyError) {
        VolleyError volleyError = (VolleyError)ex.getCause();
        if (volleyError.networkResponse != null) {
          throw new ApiException(volleyError.networkResponse.statusCode, volleyError.getMessage());
        }
      }
      throw ex;
    } catch (TimeoutException ex) {
      throw ex;
    }
  }

      /**
   * showDocumentFile2
   * showDocumentFile2
   * @param orgId orgId   * @param patientId patientId   * @param docId docId
  */
  public void showDocumentFile2UsingGET (Long orgId, Long patientId, Long docId, final Response.Listener<List<byte[]>> responseListener, final Response.ErrorListener errorListener) {
    Object postBody = null;

    // verify the required parameter 'orgId' is set
    if (orgId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'orgId' when calling showDocumentFile2UsingGET",
        new ApiException(400, "Missing the required parameter 'orgId' when calling showDocumentFile2UsingGET"));
    }
    // verify the required parameter 'patientId' is set
    if (patientId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'patientId' when calling showDocumentFile2UsingGET",
        new ApiException(400, "Missing the required parameter 'patientId' when calling showDocumentFile2UsingGET"));
    }
    // verify the required parameter 'docId' is set
    if (docId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'docId' when calling showDocumentFile2UsingGET",
        new ApiException(400, "Missing the required parameter 'docId' when calling showDocumentFile2UsingGET"));
    }

    // create path and map variables
    String path = "/orgs/{orgId}/patients/{patientId}/documents/{docId}/file/{fileName}".replaceAll("\\{format\\}","json").replaceAll("\\{" + "orgId" + "\\}", apiInvoker.escapeString(orgId.toString())).replaceAll("\\{" + "patientId" + "\\}", apiInvoker.escapeString(patientId.toString())).replaceAll("\\{" + "docId" + "\\}", apiInvoker.escapeString(docId.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();



    String[] contentTypes = {
      "application/json"
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      

      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
          }

    String[] authNames = new String[] {  };

    try {
      apiInvoker.invokeAPI(basePath, path, "GET", queryParams, postBody, headerParams, formParams, contentType, authNames,
        new Response.Listener<String>() {
          @Override
          public void onResponse(String localVarResponse) {
            try {
              responseListener.onResponse((List<byte[]>) ApiInvoker.deserialize(localVarResponse,  "array", byte[].class));
            } catch (ApiException exception) {
               errorListener.onErrorResponse(new VolleyError(exception));
            }
          }
      }, new Response.ErrorListener() {
          @Override
          public void onErrorResponse(VolleyError error) {
            errorListener.onErrorResponse(error);
          }
      });
    } catch (ApiException ex) {
      errorListener.onErrorResponse(new VolleyError(ex));
    }
  }
  /**
  * showDocumentFile
  * showDocumentFile
   * @param orgId orgId
   * @param patientId patientId
   * @param docId docId
   * @return List<byte[]>
  */
  public List<byte[]> showDocumentFileUsingGET (Long orgId, Long patientId, Long docId) throws TimeoutException, ExecutionException, InterruptedException, ApiException {
    Object postBody = null;
    // verify the required parameter 'orgId' is set
    if (orgId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'orgId' when calling showDocumentFileUsingGET",
        new ApiException(400, "Missing the required parameter 'orgId' when calling showDocumentFileUsingGET"));
    }
    // verify the required parameter 'patientId' is set
    if (patientId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'patientId' when calling showDocumentFileUsingGET",
        new ApiException(400, "Missing the required parameter 'patientId' when calling showDocumentFileUsingGET"));
    }
    // verify the required parameter 'docId' is set
    if (docId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'docId' when calling showDocumentFileUsingGET",
        new ApiException(400, "Missing the required parameter 'docId' when calling showDocumentFileUsingGET"));
    }

    // create path and map variables
    String path = "/orgs/{orgId}/patients/{patientId}/documents/{docId}/file".replaceAll("\\{" + "orgId" + "\\}", apiInvoker.escapeString(orgId.toString())).replaceAll("\\{" + "patientId" + "\\}", apiInvoker.escapeString(patientId.toString())).replaceAll("\\{" + "docId" + "\\}", apiInvoker.escapeString(docId.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();
    String[] contentTypes = {
      "application/json"
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
    }

    String[] authNames = new String[] {  };

    try {
      String localVarResponse = apiInvoker.invokeAPI (basePath, path, "GET", queryParams, postBody, headerParams, formParams, contentType, authNames);
      if (localVarResponse != null) {
         return (List<byte[]>) ApiInvoker.deserialize(localVarResponse, "array", byte[].class);
      } else {
         return null;
      }
    } catch (ApiException ex) {
       throw ex;
    } catch (InterruptedException ex) {
       throw ex;
    } catch (ExecutionException ex) {
      if (ex.getCause() instanceof VolleyError) {
        VolleyError volleyError = (VolleyError)ex.getCause();
        if (volleyError.networkResponse != null) {
          throw new ApiException(volleyError.networkResponse.statusCode, volleyError.getMessage());
        }
      }
      throw ex;
    } catch (TimeoutException ex) {
      throw ex;
    }
  }

      /**
   * showDocumentFile
   * showDocumentFile
   * @param orgId orgId   * @param patientId patientId   * @param docId docId
  */
  public void showDocumentFileUsingGET (Long orgId, Long patientId, Long docId, final Response.Listener<List<byte[]>> responseListener, final Response.ErrorListener errorListener) {
    Object postBody = null;

    // verify the required parameter 'orgId' is set
    if (orgId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'orgId' when calling showDocumentFileUsingGET",
        new ApiException(400, "Missing the required parameter 'orgId' when calling showDocumentFileUsingGET"));
    }
    // verify the required parameter 'patientId' is set
    if (patientId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'patientId' when calling showDocumentFileUsingGET",
        new ApiException(400, "Missing the required parameter 'patientId' when calling showDocumentFileUsingGET"));
    }
    // verify the required parameter 'docId' is set
    if (docId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'docId' when calling showDocumentFileUsingGET",
        new ApiException(400, "Missing the required parameter 'docId' when calling showDocumentFileUsingGET"));
    }

    // create path and map variables
    String path = "/orgs/{orgId}/patients/{patientId}/documents/{docId}/file".replaceAll("\\{format\\}","json").replaceAll("\\{" + "orgId" + "\\}", apiInvoker.escapeString(orgId.toString())).replaceAll("\\{" + "patientId" + "\\}", apiInvoker.escapeString(patientId.toString())).replaceAll("\\{" + "docId" + "\\}", apiInvoker.escapeString(docId.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();



    String[] contentTypes = {
      "application/json"
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      

      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
          }

    String[] authNames = new String[] {  };

    try {
      apiInvoker.invokeAPI(basePath, path, "GET", queryParams, postBody, headerParams, formParams, contentType, authNames,
        new Response.Listener<String>() {
          @Override
          public void onResponse(String localVarResponse) {
            try {
              responseListener.onResponse((List<byte[]>) ApiInvoker.deserialize(localVarResponse,  "array", byte[].class));
            } catch (ApiException exception) {
               errorListener.onErrorResponse(new VolleyError(exception));
            }
          }
      }, new Response.ErrorListener() {
          @Override
          public void onErrorResponse(VolleyError error) {
            errorListener.onErrorResponse(error);
          }
      });
    } catch (ApiException ex) {
      errorListener.onErrorResponse(new VolleyError(ex));
    }
  }
  /**
  * showDocument
  * showDocument
   * @param orgId orgId
   * @param patientId patientId
   * @param docId docId
   * @return String
  */
  public String showDocumentUsingGET (Long orgId, Long patientId, Long docId) throws TimeoutException, ExecutionException, InterruptedException, ApiException {
    Object postBody = null;
    // verify the required parameter 'orgId' is set
    if (orgId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'orgId' when calling showDocumentUsingGET",
        new ApiException(400, "Missing the required parameter 'orgId' when calling showDocumentUsingGET"));
    }
    // verify the required parameter 'patientId' is set
    if (patientId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'patientId' when calling showDocumentUsingGET",
        new ApiException(400, "Missing the required parameter 'patientId' when calling showDocumentUsingGET"));
    }
    // verify the required parameter 'docId' is set
    if (docId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'docId' when calling showDocumentUsingGET",
        new ApiException(400, "Missing the required parameter 'docId' when calling showDocumentUsingGET"));
    }

    // create path and map variables
    String path = "/orgs/{orgId}/patients/{patientId}/documents/{docId}".replaceAll("\\{" + "orgId" + "\\}", apiInvoker.escapeString(orgId.toString())).replaceAll("\\{" + "patientId" + "\\}", apiInvoker.escapeString(patientId.toString())).replaceAll("\\{" + "docId" + "\\}", apiInvoker.escapeString(docId.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();
    String[] contentTypes = {
      "application/json"
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
    }

    String[] authNames = new String[] {  };

    try {
      String localVarResponse = apiInvoker.invokeAPI (basePath, path, "GET", queryParams, postBody, headerParams, formParams, contentType, authNames);
      if (localVarResponse != null) {
         return (String) ApiInvoker.deserialize(localVarResponse, "", String.class);
      } else {
         return null;
      }
    } catch (ApiException ex) {
       throw ex;
    } catch (InterruptedException ex) {
       throw ex;
    } catch (ExecutionException ex) {
      if (ex.getCause() instanceof VolleyError) {
        VolleyError volleyError = (VolleyError)ex.getCause();
        if (volleyError.networkResponse != null) {
          throw new ApiException(volleyError.networkResponse.statusCode, volleyError.getMessage());
        }
      }
      throw ex;
    } catch (TimeoutException ex) {
      throw ex;
    }
  }

      /**
   * showDocument
   * showDocument
   * @param orgId orgId   * @param patientId patientId   * @param docId docId
  */
  public void showDocumentUsingGET (Long orgId, Long patientId, Long docId, final Response.Listener<String> responseListener, final Response.ErrorListener errorListener) {
    Object postBody = null;

    // verify the required parameter 'orgId' is set
    if (orgId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'orgId' when calling showDocumentUsingGET",
        new ApiException(400, "Missing the required parameter 'orgId' when calling showDocumentUsingGET"));
    }
    // verify the required parameter 'patientId' is set
    if (patientId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'patientId' when calling showDocumentUsingGET",
        new ApiException(400, "Missing the required parameter 'patientId' when calling showDocumentUsingGET"));
    }
    // verify the required parameter 'docId' is set
    if (docId == null) {
      VolleyError error = new VolleyError("Missing the required parameter 'docId' when calling showDocumentUsingGET",
        new ApiException(400, "Missing the required parameter 'docId' when calling showDocumentUsingGET"));
    }

    // create path and map variables
    String path = "/orgs/{orgId}/patients/{patientId}/documents/{docId}".replaceAll("\\{format\\}","json").replaceAll("\\{" + "orgId" + "\\}", apiInvoker.escapeString(orgId.toString())).replaceAll("\\{" + "patientId" + "\\}", apiInvoker.escapeString(patientId.toString())).replaceAll("\\{" + "docId" + "\\}", apiInvoker.escapeString(docId.toString()));

    // query params
    List<Pair> queryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> headerParams = new HashMap<String, String>();
    // form params
    Map<String, String> formParams = new HashMap<String, String>();



    String[] contentTypes = {
      "application/json"
    };
    String contentType = contentTypes.length > 0 ? contentTypes[0] : "application/json";

    if (contentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      

      HttpEntity httpEntity = localVarBuilder.build();
      postBody = httpEntity;
    } else {
      // normal form params
          }

    String[] authNames = new String[] {  };

    try {
      apiInvoker.invokeAPI(basePath, path, "GET", queryParams, postBody, headerParams, formParams, contentType, authNames,
        new Response.Listener<String>() {
          @Override
          public void onResponse(String localVarResponse) {
            try {
              responseListener.onResponse((String) ApiInvoker.deserialize(localVarResponse,  "", String.class));
            } catch (ApiException exception) {
               errorListener.onErrorResponse(new VolleyError(exception));
            }
          }
      }, new Response.ErrorListener() {
          @Override
          public void onErrorResponse(VolleyError error) {
            errorListener.onErrorResponse(error);
          }
      });
    } catch (ApiException ex) {
      errorListener.onErrorResponse(new VolleyError(ex));
    }
  }


}
